ho-dev/HattrickOrganizer

buildResources/Linux/ho.sh
=> copy db from old user directory to new directory on Linux

src/main/java/core/db/WorldDetailsTable.java
While adding new countries Palestine was duplicated which caused SQL exceptions.
=> remove duplicated country

src/main/java/module/playeranalysis/skillCompare/MyTableCellRenderer.java
fix for issue#41
issue:Player Compare Tab is missing some columns information for specific languages #41
=> fix for issue#41

src/main/java/tool/export/CsvPlayerExport.java
wrong data player export by Tool - csv export player #42
Now:
- Column name are translate
- Text value has double quote, and numerical value no
=> Fix for issue #42

.gitignore, buildResources/Linux/ho.sh, src/main/java/tool/updater/UpdateController.java, src/main/resources/sprache/English.properties
Hello,
My proposal for the warning when update via menu after install via package.
PS: add also files in .gitignore for vs code IDE.
=> Linux warn upd

.gitignore
=> Fix for issue#61

src/main/java/module/transfer/scout/MiniScoutDialog.java, src/main/java/module/transfer/scout/PlayerConverter.java, src/main/java/module/transfer/scout/TransferEingabePanel.java, src/main/java/module/transfer/scout/TransferTableModel.java, src/main/resources/changelog.txt, src/main/resources/release_notes.txt, src/main/resources/sprache/English.properties
Fix for issue#15
In the HT copy function is not present the info
- Deadline
- Price
- Mother Club
When HT get out this information, it will need update the HO!.
=> Fix for issue#15

src/main/java/core/util/Helper.java, src/main/java/core/util/LocaleResolve.java, src/main/java/module/playeranalysis/skillCompare/MyTableCellRenderer.java, src/main/java/module/transfer/history/PlayerDetailPanel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
- fixes issue #93 
- wages/prices are formatted as team local currency as opposed to host system currency
=> Currency patch (around #93)

src/main/java/module/lineup/Lineup.java
issue #44 to avoid exception
we have it when we try to download order match of a finish match
=> issue #44 to avoid exception

src/main/java/tool/export/CsvPlayerExport.java, version.properties
* In addition to akasolace/HO#51: more fixes for Tool->Export CSV.
=> Tool->Export CSV: addition to akasolace/HO#51

build.gradle
The project have to be build-able directly from-the-box.
=> A little build.gradle fix

src/main/java/core/gui/model/ArenaStatistikModel.java, version.properties
=> Fix for issue #109

src/main/java/core/file/xml/XMLCHPPPreParser.java, src/main/java/core/file/xml/XMLManager.java, src/main/java/core/net/MyConnector.java, src/main/resources/sprache/English.properties
=> issue #140

src/main/java/module/pluginFeedback/FeedbackPanel.java, src/main/java/module/teamAnalyzer/vo/MatchRating.java, src/main/java/tool/ToolManager.java, src/main/java/tool/pluginFeedback/Feedback.java, src/main/java/tool/pluginFeedback/PluginFeedback.java, version.properties
Version in order to manage send follow information:
lineupName, tactict type, tactic skill, attitude, style of play
=> Enhancement for #38

src/main/java/core/training/TrainingPreviewPlayers.java
Fixes issue #148
Exception when we started with an empty db
=> issue #148

buildResources/Linux/ho.sh
Fixes issue #149
Report of #102 on stable branch
=> Issue 149 stb

src/main/java/core/gui/comp/entry/SmilieEntry.java, src/main/java/core/model/HOModel.java, version.properties
issue #153
sorting table by squad is super slow
=> issue #153

src/main/java/module/pluginFeedback/Feedback.java, src/main/java/module/pluginFeedback/FeedbackPanel.java, src/main/java/module/pluginFeedback/PluginFeedback.java, src/main/java/tool/ToolManager.java
- Removed the unused menu entry Feedbakplugin
- Moved Feedback pluging files in module folder
@akasolace this PR is ready!
=> Enhancement for #131

src/main/java/module/lineup/AufstellungsDetailPanel.java, src/main/java/module/lineup/AufstellungsRatingPanel.java
=> moved Hatstat and Loddar values higher

src/main/java/core/gui/comp/entry/SpielerLabelEntry.java, src/main/java/core/gui/model/SpielerCBItem.java
Small modifications for issue #133 
- reduce space between select player and other players
- add shirt on the same line than player name   
For "no player previously selected, there should be no blank", it work like this before I don't touch to it.
For the player name (full name, short name, etc ...) I have no opinion, I leave you the modification you want ;)
=> issue #133 size of combo in lineup

src/main/java/core/gui/comp/entry/SpielerLabelEntry.java, src/main/java/core/gui/model/SpielerCBItem.java, src/main/java/module/lineup/LineupPositionsPanel.java, src/main/java/module/lineup/PlayerPositionPanel.java
issue #146 List of players listed in subs dropbox
=> issue #146 List of players listed in subs dropbox

src/main/java/module/lineup/CopyListener.java, version.properties
=> issue #185 copy linup+rating for HT forum

src/main/java/module/lineup/AufstellungsAssistentPanel.java
- fixes issue #194 - Hard to read suggestions in "LineUp"  
- do not require update
=> Fixes #194 - Hard to read suggestions in LineUp

list.diff, src/main/java/core/file/hrf/HRFStringParser.java, src/main/java/core/model/misc/Basics.java, src/main/java/core/model/player/Player.java, src/main/java/core/net/MyConnector.java, src/main/java/module/nthrf/NtLineupParser.java, src/main/java/module/nthrf/NtPlayer.java, src/main/java/module/nthrf/NtPlayersParser.java, src/main/java/module/nthrf/NthrfConvertXml2Hrf.java, src/main/java/module/transfer/TransfersPanel.java, src/main/java/module/transfer/history/HistoryPane.java
#107 Invalid HRF with national team
Just a doubt about this code: 
`    public boolean isNationalTeam() {
return (m_iTeamId > 0 && m_iTeamId < 5000);
}`
=> issue #107 HRF invalid for national team

src/main/java/module/nthrf/NtLineupParser.java, src/main/java/module/nthrf/NtPlayersParser.java, version.properties
fixes issue #192 first names in national teams
=> issue #192 HRF first name

src/main/java/core/model/FormulaFactors.java
- fixes issue #166 - v 2.0 1256 doesn't start on mac 
Please, before merging, check if the Windows and the Zip versions continue to work as expected.
=> #166 - v 2.0 1256 doesn't start on mac

src/main/java/module/pluginFeedback/PluginFeedback.java, version.properties
=> Enhancement for #200:

src/main/java/module/lineup/PlayerPositionPanel.java
=> issue #146 reset players combo

src/main/java/module/pluginFeedback/FeedbackPanel.java, src/main/java/module/teamAnalyzer/vo/MatchRating.java, src/main/java/tool/ToolManager.java
=> Fix for #220

src/main/java/module/training/ui/OutputPanel.java, src/main/java/module/training/ui/TrainingRecapTable.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/main/java/module/training/ui/renderer/OutputTableRenderer.java
Feature for Training Screens #222
- highlighted the player in training
=> Feature for Training Screens #222

src/main/java/core/file/xml/ConvertXml2Hrf.java
Fix for #173
It should be tested in more conditions, at least:
1) next match is friendly
2) next match is ladder
3) next match is non official match
=> Fix for #173

src/main/java/core/gui/comp/entry/SpielerLabelEntry.java
- added border in each player cell (in order to separate the cells)
- also skill in same color of the player name
- when I select with mouse the effect is text bold (other option color border), in order to understand better which player I'm selecting
new (ubuntu screenshot):
old (windows screenshot):
=> Feature for #232:

src/main/java/module/series/MatchDayPanel.java, version.properties
=> Feature for #237

src/main/java/module/training/OldTrainingManager.java, src/main/java/module/training/Skills.java, src/main/java/module/training/ui/PlayerDetailPanel.java
=> fix for #236

src/main/java/module/training/ui/comp/FutureSettingPanel.java
=> fix for #249

src/main/java/module/pluginFeedback/FeedbackPanel.java, src/main/java/module/pluginFeedback/PluginFeedback.java, src/main/resources/sprache/English.properties
- if data old 5 minutes, an message appear in order to ask download data
- logic for read "server_status" in json
- logic for url server (param: "server_url") in json (in order to overwrite the current default)
@akasolace, If you think 5 minutes are many or not, we can change the value, or we can think to include this value in json (in order to have control on this param without make new release).
Let me do you think.
=> fix for #244:

src/main/java/module/lineup/AufstellungsDetailPanel.java, src/main/java/module/lineup/MinuteTogglerPanel.java
minute toggler panel does not show when team data is unavailable
- fixes issue #254 
2. changelog and release_notes
=> fixes issue 254

src/main/java/core/rating/RatingPredictionManager.java
Issue #259 error with support speciality
=> #259 Error with support speciality

src/main/java/core/file/xml/XMLMatchOrderParser.java, version.properties
=> fix for #266

src/main/java/module/training/ui/comp/FutureSettingPanel.java
=> fix for #269

src/main/java/core/model/player/IMatchRoleID.java, src/main/java/core/net/OnlineWorker.java
#273 go back to use getPenaltyTakers because penalty takers are not in m_vPositionen
=> #273 order match: penalty takers

src/main/java/module/pluginFeedback/FeedbackPanel.java, src/main/resources/sprache/English.properties
- add check for style of play, it have to be the same in HT and HO
=> fix for #279

src/main/java/core/model/match/MatchType.java, src/main/java/core/training/TrainingPreviewPlayers.java
=> #278 training preview secondary cups

src/main/java/core/training/TrainingManager.java
=> #306 training secondary cups

src/main/java/core/model/match/MatchStatistics.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingPreviewPlayers.java, src/main/java/core/training/TrainingWeekPlayer.java
#125 
- correction for stamina in training preview (when we have substitution)
- LA-alpacstily confirm we must taken into account minutes play during off-time
=> #125 stamina training preview

src/main/java/core/model/match/MatchType.java, src/main/java/module/matchesanalyzer/data/MatchesAnalyzerMatchType.java
#310  
-for division battle we download official match instead of tournement match!
-division battle no manage in match analyzer
=> #310 division battle

src/main/java/core/training/TrainingPreviewPlayers.java
=> #311 stamina training preview

src/main/java/core/db/DBUpdater.java, src/main/java/module/lineup/Lineup.java
- fixes typo in DbUpdater
- fixes loading stored lineup bug (set pieces/kicker1 not reloaded)
- [??? ] do not require update
=> Err reload lineup

src/main/java/core/gui/comp/entry/AbstractHOTableEntry.java, src/main/java/core/gui/comp/entry/ColorLabelEntry.java, src/main/java/core/gui/comp/entry/DoppelLabelEntry.java, src/main/java/core/gui/comp/entry/HomegrownEntry.java, src/main/java/core/gui/comp/entry/IHOTableEntry.java, src/main/java/core/gui/comp/entry/ProgressbarTableEntry.java, src/main/java/core/gui/comp/entry/RatingTableEntry.java, src/main/java/core/gui/comp/entry/SkillEntry.java, src/main/java/core/gui/comp/entry/SpielerLabelEntry.java, src/main/java/core/gui/comp/entry/TorLabelEntry.java, src/main/java/core/gui/comp/table/TableSorter.java, src/main/java/core/training/TrainingPreviewPlayer.java, src/main/java/module/playerOverview/PlayerOverviewTable.java, version.properties
#124 sort by training preview
Maybe it's not the best way to do it, I'll let you have a look.
I don't do it for training page because it sorted frlom an invisible column
=> #124 sort by training preview

src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/db/MatchesOverviewQuery.java, src/main/java/core/db/StatisticQuery.java, src/main/java/module/matches/SpielePanel.java, src/main/java/module/statistics/ArenaStatistikPanel.java, src/main/java/module/statistics/SpieleStatistikPanel.java, src/main/resources/sprache/English.properties
=> #issue323 filter secondaru cups

src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/db/MatchesOverviewQuery.java, src/main/java/core/db/StatisticQuery.java, src/main/java/module/matches/SpielePanel.java, src/main/java/module/statistics/ArenaStatistikPanel.java, src/main/java/module/statistics/SpieleStatistikPanel.java, src/main/resources/sprache/English.properties
=> #326 filter qualification matches

src/main/java/core/file/hrf/HRFStringParser.java, src/main/java/core/model/HOModel.java, src/main/java/core/model/HOVerwaltung.java, src/main/java/module/matches/SpielePanel.java
- fixes issue #328
- [ x] do not require update
=> Feature previous lineup

src/main/java/core/rating/RatingPredictionManager.java
=> RatingPrediction reset starting time

src/main/java/core/file/xml/XMLMatchLineupParser.java, src/main/java/core/gui/model/ArenaStatistikModel.java, src/main/java/core/gui/model/MatchesColumnModel.java, src/main/java/core/gui/theme/HOColorName.java, src/main/java/core/gui/theme/ho/HOClassicSchema.java, src/main/java/module/specialEvents/SpecialEventsDM.java, src/main/java/module/teamAnalyzer/manager/TeamManager.java
issue #313 and other corrections for Battle matchs in
- matchs list (specific color)
- arena stats
- team analyzer combo
=> #313 division battle

src/main/java/module/series/MatchDayPanel.java
=> MatchDayPanel enhanced game finished decision

src/main/java/module/series/MatchDayPanel.java
=> Compile error

src/main/java/module/teamAnalyzer/ht/HattrickManager.java
=> err#291: TeamAnalyzer HattrickManager getIntValue fixed

src/main/java/core/net/OnlineWorker.java
=> fix npe in OnlineWorker.downloadMatchData

.github/pull_request_template.md
Fix a typo in this very template.
=> Small typo in the PR template

src/main/java/module/lineup/AufstellungsDetailPanel.java
=> #191 style of play for NT

src/main/java/core/gui/comp/panel/DoubleLabelPanel.java, src/main/java/module/playerOverview/TeamSummaryPanel.java
Changes to the team summary panel following feedback (cf. https://github.com/akasolace/HO/issues/373#issuecomment-581174071)
=> Team Summary changes following feedback

src/main/java/module/playerOverview/TeamSummaryPanel.java
Add thousand separator for delta values.
=> Add thousand separator to delta value.

src/main/resources/changelog.md, src/main/resources/release_notes.md
This adds a changelog entry as well as a release note for #377  
=> Changelog and release note for #377

src/main/java/core/db/MatchHighlightsTable.java
(cherry picked from commit 8ccf571da00f748b2c7db081c93ac1c9b80a5289)
- fixes issue #396
=> fix init MatchHighlightsTable

src/main/java/core/constants/player/Speciality.java
(cherry picked from commit c87b818e0dd6b3261ae989914afb2dc4f8d44631)
- fixes issue #425   
=> fix bug with supporter specialty

src/main/java/core/model/player/Player.java
(cherry picked from commit 5fe054c3b11507c8decd74ef225c0eea7961e85d)
- fixes issue #422  
=> beautify Player.getAgeWithDaysAsString

src/main/java/core/specialevents/ExperienceEventPredictionAnalyzer.java, src/main/java/core/specialevents/PowerfulEventPredictionAnalyzer.java, src/main/java/core/specialevents/QuickEventPredictionAnalyzer.java, src/main/java/core/specialevents/TechnicalEventPredictionAnalyzer.java, src/main/java/core/specialevents/UnpredictableEventPredictionAnalyzer.java, src/main/java/core/specialevents/WingerEventPredictionAnalyzer.java
=> Bugfixoffeature299

src/main/java/core/model/player/Player.java, src/main/java/module/playerOverview/SpielerTrainingsSimulatorPanel.java
=> bug#446: fix Player age calculation in skilltest (no hrfdate)

src/main/java/core/db/DBUpdater.java, src/main/java/core/model/player/Player.java
=> #455: DbUpdater fix exception on ownLeageuePlans access

docs/README.md
OkHttp needs to be added to the list of dependencies in the README.
=> Add new dependency to README.

src/main/java/core/net/DownloadDialog.java, src/main/java/core/net/OnlineWorker.java
=> #473: Filter Match Archive downloads

src/main/java/core/gui/comp/icon/DrawIcon.java, src/main/java/module/series/SeriesTablePanel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
Fixes #499.
- fixes issue #499
=> Fix colour of arrow in series table.

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java
- fixes issue #509
- [] do not require update
=> #509: run db update v3.00 and v3.01 again

src/main/java/core/gui/comp/entry/RatingTableEntry.java, src/main/java/module/playerOverview/SpielerDetailPanel.java
- fixes issue #485 
I add icon for match type in match link
=> Redesign PlayerDetails panel - LastMatch instead of Ranking

src/main/java/core/db/DBUpdater.java, src/main/java/core/db/VereinTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLClubParser.java, src/main/java/core/file/xml/XMLTeamDetailsParser.java, src/main/java/core/model/HOModel.java, src/main/java/core/model/misc/Verein.java, src/main/java/core/net/MyConnector.java, src/main/java/core/net/OnlineWorker.java
integrate power rating in DB
update/cleanup VEREIN table
=> first step of 454

src/main/java/core/db/DBManager.java
Issue #531: better error message
=> #531: Bad error message when db is lock

build.gradle, src/main/java/core/model/player/IMatchRoleID.java, src/main/java/core/rating/RatingPredictionManager.java, src/main/java/core/util/MathUtils.java, src/main/java/module-info.java, version.properties
=> removal of google guava dependency

src/main/java/core/net/OnlineWorker.java, src/main/resources/sprache/English.properties
New message when we cannot save hrf file
=> #462: Msg when hrf save failed

src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/module/teamAnalyzer/SystemManager.java, src/main/java/module/teamAnalyzer/manager/TeamManager.java, src/main/java/module/teamAnalyzer/ui/ComboBoxRenderer.java, src/main/java/module/teamAnalyzer/ui/FilterPanel.java, src/main/java/module/teamAnalyzer/vo/Team.java
New management of the list of the teams in the Team Analyzer combobox:
- new renderer (use icon instead of color)
- load series teams like before
- load all other match in one request
- team order in combobox correspond to the date of the matchs
=> #537: Modify Team Analyzer combo

src/main/java/core/db/User.java
Application files go into `~/Library/Application Support/HO`.
(Also cleaned up lots of empty lines)
Cf. above.
=> Fix macOS directory location.

src/main/java/core/gui/model/PlayerAnalysisModel.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/module/playeranalysis/SpielerAnalysePanel.java
Double click on row in Player Analysis open Match report
Click+SHIFT on row in Player Analysis open ht website
For this purpose I need that column 54 - MatchID would be locked.
Somebody need to test URL in linux and mac!!!
I use firefox for linux, and firefox must be in root path. Maybe I can test tommorow at office (we use centos).
=> Double click and click+shift

src/main/java/core/model/match/MatchType.java, src/main/java/module/playerOverview/SpielerDetailPanel.java
#547 
I add link to hattrick match by Id
I also add method `isCupMatch` in class MatchType because for hattrick it is official match. I didn't want to change the method `isOfficial`.
When you merge all branches we must change for #569 this condition and create one class or method for web pages.
=> SHIFT + click to WEB page for matchId

src/main/java/core/model/player/IMatchRoleID.java, src/main/java/core/rating/RatingPredictionManager.java, src/main/resources/changelog.md, src/main/resources/prediction/new/tactics.dat, src/main/resources/prediction/predictionTypes.conf, src/main/resources/release_notes.md, version.properties
=> fix LS tactic calculation

src/main/java/core/training/FutureTrainingManager.java
- fixes issue #587  (not completly)
=> #587: fix trainingspeed calculation

src/main/java/module/lineup/Lineup.java
Exception when clean a lineup and when we have a "nex behaviour" order
=> #573: Exception when clean a lineup with new behaviour

src/main/java/core/gui/comp/entry/LastMatchLabelEntry.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/module/playerOverview/SpielerDetailPanel.java
#461 
LastMatch column (date + rating) order by date, rating
Resolve bug on PlayerDetailPanel ... clear add before set last match info
Notice: Last match is not translated for Serbian(cyrillic)
=> LastMatch column (date + rating) order by date, rating

src/main/java/core/gui/comp/entry/SpielerLabelEntry.java, src/main/java/core/gui/theme/HOColorName.java, src/main/java/core/gui/theme/dark/DarculaDarkTheme.java, src/main/java/core/gui/theme/dark/SolarizedDarkTheme.java, src/main/java/core/gui/theme/ho/HOClassicSchema.java
Fixes #612, thanks @yaute74 for the analysis!
- fixes issue #612 
3. [Optional] suggested person to review this PR @yaute74
=> Restore highlight of selected players, based on themes.

src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/module/teamAnalyzer/SystemManager.java, src/main/java/module/teamAnalyzer/manager/TeamManager.java, src/main/java/module/teamAnalyzer/ui/ComboBoxRenderer.java, src/main/java/module/teamAnalyzer/ui/FilterPanel.java, src/main/java/module/teamAnalyzer/vo/Team.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
Cherry-picked da4f3a4a9c7a1b4a2757c0793f6f0cea0c9bee75 to address issue #625 
- fixes issue #625 
3. [Optional] suggested person to review this PR @yaute74
=> Show consolation cup in 3.x release

src/main/java/core/file/hrf/HRFImport.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/lineup/AufstellungsNameDialog.java, src/main/java/module/lineup/LineupPanel.java, src/main/java/module/lineup/LineupPositionsPanel.java
fixes #635
- remove exportOldLineup()
- fixes issue #635
@tychobrailleur @wsbrenk made some quick tests and I did not see unwanted side effects (tbc)
=> remove exportOldLineup()

src/main/java/core/db/user/User.java, src/main/java/core/util/HOLogger.java, utils/buildResources/HO.install4j
- consolidate all log files in the log directory
- fixes issues #622 and #591
=> Move logs folder

src/main/java/core/training/FuturePlayerTraining.java
- fixes npe in FuturePlayerTraining.cut which was introduced for the individual trainings plans
=> npe in FuturePlayerTraining.cut

src/main/java/core/db/DBManager.java, src/main/java/core/db/PaarungTable.java, src/main/java/core/db/SpielplanTable.java, src/main/java/module/series/MatchDayPanel.java, src/main/java/module/series/Spielplan.java, src/main/java/module/teamOfTheWeek/gui/MatchLineupPlayer.java, src/main/java/module/teamOfTheWeek/gui/TeamOfTheWeekPanel.java
Change vectors into lists, and translate comments.  Also fix a SQL
Exception that was thrown in `SpielPlan#storeSpielplan`.
Cf. above.
=> Cleanup of Spieplan and Paarungen.

src/main/java/core/model/player/Player.java, src/main/resources/sprache/English.properties
fine tuning of indivdual training plan feature
=> Training table priority column contents

utils/pythonScripts/UpdateLeagueStatusDetailsTable.py
=> closes #581

build.gradle, src/main/java/core/HO.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/model/UserParameter.java, src/main/java/core/util/Updater.java, version.properties
=> fix #667 and #669

build.gradle, src/main/java/core/db/MatchDetailsTable.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/core/model/match/Matchdetails.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/playerOverview/SpielerUebersichtsPanel.java
as mentioned in #660 
- [x ] do not require update
3. [Optional] suggested person to review this PR @akasolace 
sorry @akasolace, again i changed the build.gradle
=> fix recursion in player overview panel (HOMainFrame constructor)

src/main/java/core/net/HattrickLink.java, src/main/java/module/lineup/AustellungSpielerTable.java, src/main/java/module/playerOverview/PlayerOverviewTable.java, src/main/java/module/playerOverview/SpielerDetailPanel.java, src/main/java/module/playerOverview/SpielerUebersichtNamenTable.java, src/main/java/module/playeranalysis/SpielerAnalysePanel.java
- fixes issue #609 
Hattrick link on player and matched from table in lineup and squad tab. 
Link on player is from column Name.
=> Hattrick links on player and match from table

src/main/java/core/file/xml/xmlPlayersParser.java, src/main/java/core/gui/comp/entry/SmilieEntry.java, src/main/java/core/gui/theme/ho/HOClassicSchema.java, src/main/java/core/model/player/IMatchRoleID.java, src/main/java/core/net/MyConnector.java, src/main/java/core/util/HTCalendar.java, src/main/java/module/lineup/Lineup.java, src/main/java/module/lineup/substitution/SubstitutionDataProvider.java, src/main/java/module/lineup/substitution/SubstitutionEditDialog.java, src/main/java/module/lineup/substitution/SubstitutionEditView.java, src/main/java/module/lineup/substitution/SubstitutionOverview.java, src/main/java/module/lineup/substitution/plausibility/Error.java, src/main/java/module/lineup/substitution/plausibility/PlausibilityCheck.java, src/main/java/module/teamAnalyzer/ht/HattrickManager.java, src/main/java/module/teamAnalyzer/ui/TeamLineupData.java, src/main/java/module/teamAnalyzer/ui/TeamPanel.java, src/main/java/module/teamAnalyzer/vo/PlayerInfo.java, src/main/java/module/teamAnalyzer/vo/TeamLineup.java, src/main/resources/changelog.md, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #660 display man marking order

src/main/java/core/gui/model/PlayerOverviewModel.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/module/lineup/LineupTableModel.java
- fixes issue #484
Reordering columns in squad and lineup tab. Not exactly the same
=> Reordering columns in squad and lineup tab

src/main/java/core/gui/theme/GroupTeam.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/lineup/Lineup.java, version.properties
- fixes issue #594
3. [Optional] suggested person to review this PR @tychobrailleur or @wsbrenk
=> closes #597

build.gradle, src/main/java/core/db/BasicsTable.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLWorldDetailsParser.java, src/main/java/core/model/misc/Basics.java, src/main/java/core/util/HTCalendarFactory.java, version.properties
=> #679 HTCalendarFactory.getSeasonOffset

src/main/java/core/util/HTCalendarFactory.java
=> #539 use SeasonOffset of worlddetails as HTCalendarFactory correction

src/main/java/core/model/UserParameter.java
=> #705 edit release channel config

src/main/java/core/gui/theme/ImageUtilities.java
=> #710 fix npe when ht country is not yet in HO worlddetails

src/main/java/core/db/DBUpdater.java, src/main/java/core/model/UserParameter.java
=> fixes #667. Test is successful.

src/main/java/core/model/player/Player.java, src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingPreviewPlayers.java, src/main/java/core/training/TrainingWeekPlayer.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/core/training/type/ShootingWeeklyTraining.java, src/main/java/module/training/ui/model/TrainingModel.java
=> #714 fix bug in shooting training prediction

utils/buildResources/HO.install4j
=> closes #707

src/main/java/module/lineup/substitution/SubstitutionEditView.java
=> #728SubstitutionEditView

src/main/java/module/lineup/Lineup.java
=> #730 fix bug in Lineup.setSpielerAtPosition

src/main/java/core/rating/RatingPredictionManager.java, src/main/java/module/teamAnalyzer/ui/TeamPanel.java, src/main/java/module/teamAnalyzer/ui/lineup/FormationPanel.java, version.properties
next step of displaying man marking order in the teamanalyzer panel.
same as previous pull request, but rebased commits.
=> Display man marking rebased

docs/README.md
repair install4j link in readme.md
=> README.md install4j products path

src/main/java/core/module/ModuleConfigPanelTable.java, src/main/java/core/option/db/DatabaseOptionsDialog.java, src/main/java/core/option/db/DatabaseUserEditDialog.java
=> fixes #706

src/main/java/module/teamAnalyzer/ui/TeamPanel.java, src/main/java/module/teamAnalyzer/vo/PlayerInfo.java
=> #739 team analyzer update own lineup

build.gradle, src/main/java/module/lineup/AustellungSpielerTable.java, src/main/java/module/lineup/LineupTableModel.java
=> code cleaning

src/main/java/core/model/XtraData.java, src/main/java/core/net/DownloadDialog.java, src/main/java/module/training/ui/PlayerDetailPanel.java, version.properties
- fixes issue #715  
for future seasons no more two fixtures per season should be stored in database.  
=> #715 do not store fixtures in week 16

src/main/java/core/db/MatchHighlightsTable.java, src/main/java/core/file/xml/XMLMatchdetailsParser.java, src/main/java/core/model/match/Matchdetails.java, src/main/java/core/net/MyConnector.java
=> closes #757

src/main/java/core/file/xml/XMLMatchLineupParser.java, src/main/java/core/net/OnlineWorker.java, version.properties
=> #751download match history

src/main/java/core/training/TrainingPreviewPlayers.java
- fixes issue #735 (the npe part of that issue)
=> #735 npe on TrainingPreviewPlayers without Matchdetails in database

src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLTeamDetailsParser.java, src/main/java/core/model/match/Matchdetails.java, src/main/java/core/net/MyConnector.java, src/main/java/core/net/OnlineWorker.java
=> #767 MyConnector.silentDownload

build.gradle, docs/latest.html, docs/latestbeta.html, src/main/java/tool/updater/UpdateController.java, src/main/java/tool/updater/Version.java, src/main/java/tool/updater/VersionInfo.java, src/test/java/tool/updater/VersionTest.java, version.properties
=> tentative closing #742

src/main/java/core/gui/theme/HOColorName.java, src/main/java/core/gui/theme/HOIconName.java, src/main/java/core/gui/theme/dark/DarculaDarkTheme.java, src/main/java/core/gui/theme/dark/SolarizedDarkTheme.java, src/main/java/core/gui/theme/ho/HOClassicSchema.java, src/main/java/core/gui/theme/light/SolarizedLightTheme.java, src/main/java/module/lineup/LineupPositionsPanel.java, src/main/java/module/lineup/PlayerPositionPanel.java, src/main/java/module/lineup/SwapPositionFeature.java
border colors have been thamed.
couple of visual fixes
small refactoring
=> Theming lineup panel

src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/net/OnlineWorker.java, src/main/java/core/training/TrainingPerWeek.java
=> #781 fix training calculation if training and matches were downloaded in one run

src/main/java/core/db/DBManager.java, src/main/java/core/gui/HOMainFrame.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
This fixes the problem locally, but it would be great to have other people's feedback on that one to see if this fixes it everywhere. 
Also add further logging that will help later if someone encounters the same issue.
- fixes issue #811 
=> Make `isAppTerminated` atomic boolean.

src/main/java/core/db/DBManager.java, src/main/java/core/gui/HOMainFrame.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
Same as #822 but on 4.x release branch, thanks @wsbrenk for the advice (I hadn't even thought about it).
- fixes issue #811 
=> 4.x release branch: Make `isAppTerminated` atomic boolean.

src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/net/MyConnector.java
- fixes NPE discovered by @tychobrailleur 
=> #367 fix ConvertXml2Hrf youthteamId NPE

src/main/java/core/db/DBManager.java, src/main/java/core/db/YouthPlayerTable.java, src/main/java/core/db/YouthScoutCommentTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/TeamInfo.java, src/main/java/core/file/xml/XMLTeamDetailsParser.java, src/main/java/core/file/xml/xmlPlayersParser.java, src/main/java/core/model/misc/Basics.java, src/main/java/core/model/player/CommentType.java, src/main/java/core/model/player/Specialty.java, src/main/java/core/model/player/YouthPlayer.java, src/main/java/core/net/MyConnector.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/training/Skills.java, src/main/java/module/youth/SkillInfoColumn.java, src/main/java/module/youth/YouthPlayerOverviewTable.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java
again a bunch of changes concerning youth module
=> #367youthcontinued

src/main/java/core/file/xml/XMLMatchLineupParser.java
- fixes refactor issue from october
=> fix XMLMatchLineupParser.createTeam create start player

src/main/java/core/db/DBUpdater.java, src/main/java/core/file/hrf/HRFFileParser.java, src/main/java/core/file/hrf/HRFImport.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLTabelleParser.java, src/main/java/core/gui/comp/renderer/HODefaultTableCellRenderer.java, src/main/java/core/model/enums/RatingsStatistics.java, src/main/java/core/model/series/LigaTabelle.java, src/main/java/core/model/series/SerieTableEntry.java, src/main/java/core/net/MyConnector.java, src/main/java/module/series/FormLabel.java, src/main/java/module/series/Model.java, src/main/java/module/series/SeriesPanel.java, src/main/java/module/series/SeriesTablePanel.java, src/main/java/module/series/Spielplan.java, src/main/java/module/series/statistics/DataDownloader.java, src/main/resources/sprache/English.properties
=> initial work on supporting stastistics in league panel (wip)

src/main/java/core/db/AbstractTable.java, src/main/java/core/db/DBUpdater.java
=> convenience method tryAddColumn

src/main/java/core/db/AufstellungTable.java, src/main/java/module/youth/TrainingDevelopmentEntry.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthTraining.java
=> #840 init column aufstellung.sourcesystem

src/main/java/core/gui/HOMainFrame.java, src/main/java/core/prediction/MatchEnginePanel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #865 tuning MatchEnginePanel.calculateNMatches

src/main/java/core/model/player/Player.java, src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingWeekPlayer.java, src/main/java/core/training/WeeklyTrainingType.java
=> #795refactoring training calculation

build.gradle, src/main/java/core/net/HattrickAPI.java, src/main/java/core/net/MyConnector.java, src/main/java/core/net/login/OAuthDialog.java
=> bump version of scribe library

src/main/java/module/lineup/LineupSettingsPanel.java
- issue #859
hi @akasolace, could it be that setLabels is called when it isn't expected to be called? I don't know, if this will fix or help fixing ticket #859
=> #859 fix npe in LineupSettingsPanel.setLabels

src/main/java/core/option/FormelPanel.java, src/main/java/core/option/SliderPanel.java, src/main/java/module/playerOverview/PlayerSubskillOffsetDialog.java
=> fixes #782

src/main/java/core/model/player/Player.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingPoints.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/core/training/type/CrossingWeeklyTraining.java, src/main/java/core/training/type/DefendingWeeklyTraining.java, src/main/java/core/training/type/DefensivePositionsWeeklyTraining.java, src/main/java/core/training/type/GoalkeepingWeeklyTraining.java, src/main/java/core/training/type/PlaymakingWeeklyTraining.java, src/main/java/core/training/type/ScoringWeeklyTraining.java, src/main/java/core/training/type/SetPiecesWeeklyTraining.java, src/main/java/core/training/type/ShootingWeeklyTraining.java, src/main/java/core/training/type/ShortPassesWeeklyTraining.java, src/main/java/core/training/type/ThroughPassesWeeklyTraining.java, src/main/java/core/training/type/WingAttacksWeeklyTraining.java
- issue #250 test proposed formula 
=> #250alternative training formula

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerDetailsTableModel.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthPlayerView.java
init table sorter of the tables youthplayeroverview and youthplayerdetails
=> #367 TableSorter

.gitignore, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/core/model/misc/Basics.java
=> fixes #868

src/main/java/core/model/HOModel.java, src/main/java/core/training/TrainingPerWeek.java
=> #795 fix TrainingPerWeek.getMatches to get sapphire cup matches

src/main/java/core/db/UserColumnsTable.java, src/main/java/core/gui/HOMainFrame.java, src/main/java/core/gui/comp/table/HOTableModel.java, src/main/java/core/gui/model/YouthPlayerColumn.java, src/main/java/core/module/DefaultModule.java, src/main/java/core/module/IModule.java, src/main/java/module/youth/TrainingDevelopmentEntry.java, src/main/java/module/youth/YouthModule.java, src/main/java/module/youth/YouthPanel.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerDetailsColumn.java, src/main/java/module/youth/YouthPlayerDetailsTableModel.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/module/youth/YouthTraining.java, src/main/java/module/youth/YouthTrainingView.java, src/main/java/module/youth/YouthTrainingViewTableModel.java, src/main/resources/sprache/English.properties
=> #367youth column order

src/main/java/core/constants/TrainingType.java, src/main/java/core/db/FutureTrainingTable.java, src/main/java/core/model/XtraData.java, src/main/java/core/model/match/MatchType.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingPerPlayer.java, src/main/java/core/training/TrainingPerWeek.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/core/util/DateTimeInfo.java, src/test/java/core/training/TrainingManagerTest.java
=> Refactor training calculation

docs/module_training.rst, src/main/java/core/db/TrainingsTable.java, src/main/java/core/db/YouthPlayerTable.java, src/main/java/core/gui/HOMainFrame.java, src/main/java/core/model/HOModel.java, src/main/java/core/module/DefaultModule.java, src/main/java/core/module/IModule.java, src/main/java/core/training/TrainingPerWeek.java, src/main/java/module/youth/SkillInfoColumn.java, src/main/java/module/youth/YouthModule.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerDetailsColumn.java, src/main/java/module/youth/YouthPlayerDetailsTableModel.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/java/module/youth/YouthSkillInfoColumn.java, src/main/java/module/youth/YouthSkillsInfo.java, src/main/java/module/youth/YouthTraining.java, src/main/java/module/youth/YouthTrainingDevelopmentEntry.java, src/main/resources/changelog.md, src/main/resources/release_notes.md, src/main/resources/youthtraining.md
=> #367 skill info column label

src/main/java/core/model/HOModel.java, src/main/java/core/model/player/Player.java, src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingPerWeek.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/core/training/type/CrossingWeeklyTraining.java, src/main/java/core/training/type/DefendingWeeklyTraining.java, src/main/java/core/training/type/DefensivePositionsWeeklyTraining.java, src/main/java/core/training/type/GoalkeepingWeeklyTraining.java, src/main/java/core/training/type/IndividualWeeklyTraining.java, src/main/java/core/training/type/PlaymakingWeeklyTraining.java, src/main/java/core/training/type/ScoringWeeklyTraining.java, src/main/java/core/training/type/SetPiecesWeeklyTraining.java, src/main/java/core/training/type/ShootingWeeklyTraining.java, src/main/java/core/training/type/ShortPassesWeeklyTraining.java, src/main/java/core/training/type/ThroughPassesWeeklyTraining.java, src/main/java/core/training/type/WingAttacksWeeklyTraining.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/main/java/module/youth/YouthPanel.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/module/youth/YouthSkillInfoColumn.java, src/main/resources/sprache/English.properties
=> Training calc refactoring use TrainingPerWeek.getAssistantLevel instead of getStaff

src/main/java/core/db/AbstractTable.java, src/main/java/core/db/DBUpdater.java
3. [Optional] suggested person to review this PR @akasolace 
Proposal for training update step 1.
can not debug since master is broken
=> Trainingtable upgrade

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/TrainingsTable.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/core/util/DateTimeInfo.java, src/main/java/module/training/ui/model/PastTrainingsTableModel.java
This is the function that will allow to save TPW vector inside TRAINING table
=> Strore tpw inside trainings table

src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/PlayerSkillChange.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/test/java/core/training/TrainingManagerTest.java
=> #903 OutputTableModel

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/FutureTrainingTable.java, src/main/java/core/training/TrainingPreviewPlayers.java, version.properties
=> #903 training refactor cont

src/main/java/core/db/FutureTrainingTable.java, src/main/java/core/model/player/Player.java, src/main/java/core/training/FuturePlayerTraining.java, src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/HattrickDate.java, src/main/java/module/training/ui/TrainingRecapPanel.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/main/java/module/training/ui/model/TrainingModel.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java
- fixes NPE in Youthplayer overview when player exists without last match date
=> #367 fix youthplayer overview match date

src/main/java/core/HO.java, src/main/java/core/model/HOModel.java, src/main/java/core/training/TrainingManager.java
HO does not currently start on master with a pristine setup, i.e. no db created yet, and HRF downloaded yet.  This checks with this is the first start when:
- Checking for HRF presence,
- Attempting to update DB config.
There is still currently an issue when going to the Training tab, as `TrainingWeekManager.getNextWeekTraining` cannot return anything yet. (not too sure how to solve this)
Cf. above.
=> Check whether this is first start when checking for HRF presence

src/main/java/core/db/DBManager.java, src/main/java/core/db/HRFTable.java, src/main/java/core/db/TrainingsTable.java, src/main/java/core/model/HOModel.java, src/main/java/core/model/HOVerwaltung.java, src/main/java/core/model/match/MatchLineup.java, src/main/java/core/model/player/Player.java, src/main/java/core/net/OnlineWorker.java, src/main/java/core/training/TrainingPerPlayer.java, src/main/java/core/training/WeeklyTrainingType.java
=> #903 debug training calculation

src/main/java/module/teamAnalyzer/SystemManager.java, src/main/java/module/teamAnalyzer/ui/AutoFilterPanel.java, src/main/java/module/teamAnalyzer/ui/FilterPanel.java, src/main/java/module/teamAnalyzer/ui/ManualFilterPanel.java
=> fixes #913

src/main/java/core/gui/comp/CheckBoxTree/CheckBoxTree.java
=> Prevent NPE when hovering on partially hidden entry.

src/main/java/core/model/player/Player.java, src/main/java/core/training/FuturePlayerTraining.java
- fixes NPE part of issue #935  
=> #935 fix npe in Player.setFutureTraining

src/main/java/core/training/HattrickDate.java
=> #935 fix individual training plan

src/main/java/core/net/OnlineWorker.java, src/main/java/module/lineup/LineupSettingsPanel.java
=> fixes #945

src/main/java/core/gui/model/YouthPlayerColumn.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerDetailsTableModel.java, src/main/java/module/youth/YouthSkillInfoColumn.java, src/main/java/module/youth/YouthTraining.java, src/main/java/module/youth/YouthTrainingDevelopmentEntry.java
=> Youth find specialties

src/main/java/core/db/DBUpdater.java, src/main/java/core/db/MatchDetailsTable.java, src/main/java/core/gui/comp/renderer/HODefaultTableCellRenderer.java, src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingPerPlayer.java, src/main/java/core/training/TrainingPerWeek.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/main/java/module/youth/YouthPlayerOverviewTableCellRenderer.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/module/youth/YouthSkillInfoColumn.java, src/main/resources/sprache/English.properties, src/test/java/core/util/HTDatetimeTest.java
- fixes issues 
- #975 , 
- #976 (NPE recentTraining without matches)
- #978 (NPE TrainingManager on fresh DB)
- #979 MatchDetailsTable constraint primary Key (MAtchId, SourceSystem)
=> #975 fix OutputTableModel

src/main/java/core/model/player/Player.java
=> handle skill downs without trainings on monday

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/model/HOModel.java, src/main/java/core/model/HOParameter.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/training/TrainingWeekManager.java
- fixes issues
- #968 
- #982  
=> #982 npes on fresh db

src/main/java/core/model/player/Player.java, src/main/java/core/training/TrainingPerPlayer.java, src/main/java/core/training/TrainingPerWeek.java
=> #984 skill downs

src/main/java/module/youth/YouthPlayerView.java, src/main/resources/sprache/English.properties
youth player details shows scout comment
=> #367 youth scout comments

src/main/java/module/series/statistics/DataDownloader.java
=> #995 npe DataDownloader

src/main/java/core/gui/theme/ThemeManager.java
=> #999 ThemeManager.getClubLogo 0 byte jpg

src/main/java/core/net/MyConnector.java, src/main/java/core/net/login/OAuthDialog.java, src/main/java/module/youth/YouthPlayerColumn.java, src/main/java/module/youth/YouthPlayerDetailsColumn.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthPlayerView.java
=> #1004 fix youth view recursions

src/main/java/module/training/ui/TrainingPredictionPanel.java, src/main/java/module/training/ui/TrainingRecapTable.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> Training recap table refactoring

src/main/java/module/teamAnalyzer/ui/lineup/FormationPanel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #956 fix npe in team analyzer's formation panel

src/main/java/module/lineup/ratings/LineupRatingPanel.java
=> #992 fix LineupRatingPanel wingback rating sides swapped

src/main/java/module/series/statistics/DataDownloader.java
=> closes #995

src/main/java/module/playerOverview/SpielerDetailPanel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #1023 adjusting experience subskill is displayed in player details panel

src/main/java/module/playerOverview/SpielerDetailPanel.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthTraining.java, src/main/java/module/youth/YouthTrainingDevelopmentEntry.java
fix bug in YouthPlayer.adjustSkill
=> Youth p layer adjust skill

src/main/java/core/option/GeneralSettingsPanel.java, src/main/java/core/option/TrainingPreferencesPanel.java, src/main/java/core/training/FutureTrainingManager.java, src/main/java/module/training/ui/model/OutputTableModel.java
=> #1030 preference future trainings exception

src/main/resources/release_notes.md
- missing release_notes update for #1032
=> Release notes update for #1032

src/main/java/core/net/DownloadDialog.java, src/main/java/core/option/ReleaseChannelPanel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #1019 check for update upon hrf download

build.gradle, src/main/java/core/gui/comp/CheckBoxTree/CheckBoxTree.java
=> Revert #934 change, and upgrade darklaf.

src/main/java/core/db/DBUpdater.java, src/main/java/core/file/xml/XMLMatchdetailsParser.java, src/main/java/core/net/OnlineWorker.java
=> continue work on matchType transition

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/MatchLineupTable.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/file/xml/XMLMatchdetailsParser.java, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/core/model/match/Matchdetails.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/net/MyConnector.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/lineup/Lineup.java, version.properties
=> continue work on #1053

src/main/java/core/db/AbstractTable.java, src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/MatchDetailsTable.java, src/main/java/core/db/MatchHighlightsTable.java, src/main/java/core/db/MatchLineupTable.java, src/main/java/core/db/YouthTrainingTable.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/enums/MatchType.java, src/main/java/core/model/match/MatchLineup.java, src/main/java/core/model/match/Matchdetails.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/net/OnlineWorker.java, src/main/java/core/util/HelperWrapper.java, src/main/java/module/matches/TeamsRatingPanel.java, src/main/java/module/statistics/MatchesStatisticsPanel.java, src/main/java/module/teamAnalyzer/manager/MatchPopulator.java, src/main/java/module/youth/YouthTraining.java, src/main/java/tool/export/XMLExporter.java
youth module is working again.
=> youth matchType refactoring

src/main/java/core/db/DBUpdater.java, src/main/java/core/db/TAPlayerTable.java, src/main/java/core/file/hrf/HRF.java, src/main/java/module/teamAnalyzer/SystemManager.java, src/main/java/module/teamAnalyzer/manager/PlayerDataManager.java, src/main/java/module/teamAnalyzer/ui/PlayerPanel.java, src/main/java/module/teamAnalyzer/vo/SpotLineup.java, src/main/java/module/teamAnalyzer/vo/UserTeamSpotLineup.java
=> fix PlayerDataManager.getCurrentHTSeason /Week performance issue

src/main/java/module/lineup/assistant/LineupAssistantPanel.java, src/main/java/module/lineup/lineup/LineupPositionsPanel.java
=> #1061 fix exclude last lineup

src/main/java/core/model/player/Player.java
=> #1082 fix Player.calcSubskills

src/main/java/core/constants/player/PlayerAbility.java, src/main/java/module/lineup/lineup/LineupPositionsPanel.java
=> #1086 fix PlayerAbility.getNameForSkill and lineup rating refresh

src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/gui/comp/entry/MatchDateTableEntry.java, src/main/java/core/gui/model/ArenaStatistikModel.java, src/main/java/core/gui/model/ArenaStatistikTableModel.java, src/main/java/core/gui/model/MatchOrdersCBItem.java, src/main/java/core/gui/model/PlayerAnalysisModel.java, src/main/java/core/gui/model/PlayerMatchCBItem.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/enums/MatchType.java, src/main/java/core/model/enums/MatchTypeExtended.java, src/main/java/core/model/match/IMatchType.java, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/core/net/OnlineWorker.java, src/main/java/core/specialevents/SpecialEventsPredictionManager.java, src/main/java/core/training/TrainingPerPlayer.java, src/main/java/module/lineup/lineup/MatchAndLineupSelectionPanel.java, src/main/java/module/lineup/lineup/MatchBanner.java, src/main/java/module/matches/StaerkenvergleichPanel.java, src/main/java/module/opponentspy/OpponentTeam/PlayedPosition.java, src/main/java/module/playerOverview/SpielerDetailPanel.java, src/main/java/module/teamAnalyzer/manager/MatchPopulator.java, src/main/java/module/teamAnalyzer/manager/TeamLineupBuilder.java, src/main/java/module/teamAnalyzer/manager/TeamManager.java, src/main/java/module/teamAnalyzer/ui/ManualFilterPanel.java, src/main/java/module/teamAnalyzer/ui/RecapPanel.java, src/main/java/module/teamAnalyzer/ui/RecapTableRenderer.java, src/main/java/module/teamAnalyzer/vo/Filter.java, src/main/java/module/teamAnalyzer/vo/Match.java, src/main/java/module/teamAnalyzer/vo/TeamLineup.java
* fix #1083
* repairs experience calculation 
* national friendly increase is set to new hattrick parameters (2d->1d).
* other new categories of experience increments of national team matches are not implemented yet (TODOs)
* ticket #1089 should stay open to handle these TODOs.
=> #1089 fix bug in experience calculation concerning MatchTypeExtended

src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/module/teamAnalyzer/SystemManager.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #1049 fix team analyzer's display of national team matches

src/main/java/module/youth/YouthTrainingDevelopmentEntry.java
=> #1095 fix bug in YouthTrainingDevelopmentEntry.findSpecialty

src/main/java/module/training/ui/model/TrainingModel.java
=> #1097 fix TrainingModel.isPartialTrainingAvailable

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/core/model/match/TournamentType.java, src/main/java/core/model/player/Player.java, src/main/java/core/training/TrainingPerPlayer.java, src/main/java/core/training/TrainingPerWeek.java, src/main/java/module/youth/YouthPanel.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/java/module/youth/YouthSkillsInfo.java, src/main/java/module/youth/YouthTrainingDevelopmentEntry.java, src/main/java/module/youth/YouthTrainingView.java, src/main/java/module/youth/YouthTrainingViewTableModel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
* fix #1089 
* youth player view is refreshed when training is edited
=> YouthTrainingViewTableModel refresh YouthPlayerView

src/main/java/module/lineup/lineup/LineupPositionsPanel.java
=> #1065 LineupPositionsPanel.refresh lineup settings

src/main/java/core/training/SkillDrops.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #1080skill losses only begin at the age of 28 years

.github/workflows/release-beta.yml, .github/workflows/release-dev.yml, .github/workflows/release.yml, version.properties
=> Releasepipelinetags

.github/workflows/release-dev.yml, build.gradle, version.properties
workflow creates new version.properties file including version property.
the file is copied to the artifacts folder
=> Release dev workflow

.github/workflows/release-dev.yml, build.gradle, version.properties
compileJava depends on PreparingBuild
=> Release dev workflow2

build.gradle
=> release-dev.yml add 3710 to run_number

build.gradle, version.properties
=> build.gradle build_number as integer

.github/workflows/release-dev.yml, build.gradle, version.properties
=> Release dev workflow6

.github/workflows/release-dev.yml, build.gradle, version.properties
=> fix artifact names (version part)

.gitignore, gradle.properties
=> restore gradle.properties

src/main/java/core/constants/player/PlayerAbility.java, src/main/java/module/teamAnalyzer/ui/RatingUtil.java
=> #1118 fix RatingUtil.getRating

src/main/java/core/db/DBUpdater.java, src/main/java/core/db/XtraDataTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/TeamInfo.java, src/main/java/core/file/xml/XMLWorldDetailsParser.java, src/main/java/core/model/HOModel.java, src/main/java/core/model/XtraData.java, src/main/java/core/util/CurrencyUtils.java, src/main/java/core/util/Helper.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #1101 fix currency format of team in foreign countries

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthSkillInfo.java
improve youth player's potential calculation 
=> Youth skill info.useful training threshold

src/main/java/core/model/HOModel.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthTrainingDevelopmentEntry.java
fix bug on youth player overview after change of trainings
=> Youth training recalc maintains current skill levels

gradle.properties
=> #1129 fix gradle.properties

.gitignore, gradle.properties
ignore gradle.properties file (last unsuccessful release run was caused by local changes in my properties, which never should be pushed to upstream/master)
=> ignore gradle.properties (try again)

.github/workflows/release-dev.yml, .gitignore, gradle.properties
=> Ignoregradleproperties

.github/workflows/release-dev.yml, build.gradle
=> build.gradle install4jHomeDir=System.getenv('INSTALL4J_HOME')

.github/workflows/release-dev.yml, .gitignore, build.gradle, gradle.properties
=> Revertgradlepropertiescommits

src/main/java/module/youth/YouthPlayerOverviewTableModel.java
fix update of youth player overview when trainings are changed
=> fix update of youth player overview

src/main/java/module/lineup/lineup/PlayerPositionPanel.java
- fixes issue #1129  
- [] do not require update
=> #1129 fix arrow orientation

src/main/java/core/db/MatchesOverviewQuery.java
=> #470 fix MatchesOverviewQuery.getMatchLocationWhereClause

build.gradle, src/main/java/core/file/FileLoader.java
test build.gradle poeditorPull dependency
=> #1135 build.gradle dependencies poeditorPull

build.gradle, src/main/java/core/file/FileLoader.java
=> #1135build

build.gradle
=> #1135 build.gradle all artifacts

build.gradle
=> #1135buildcnt

.github/workflows/release-dev.yml, build.gradle
=> #1135 test git cmds

.github/workflows/release-dev.yml, build.gradle
=> Build git cmds

.github/workflows/release-dev.yml
=> release action shall run on release branches too

.github/workflows/release-dev.yml, build.gradle
=> Start release branch action

src/main/java/core/gui/theme/ho/HOClassicSchema.java
=> #1172 fix HOClassicSchema.initColors red color name

src/main/java/core/db/TransferTable.java
=> #1172 fix error in TransferTable.updateTeamTransfers

src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #779 update release notes

src/main/java/core/db/DBManager.java, src/main/java/core/model/misc/Basics.java
=> #1175 fix DBManager.instance init parentFolder

build.gradle, src/main/java/core/db/DBManager.java, src/main/java/core/model/misc/Basics.java
=> #779start beta

.github/workflows/release-dev.yml
=> #779 build.gradle branch_name

src/main/java/core/db/MatchTeamRatingTable.java
=> #1200 fix MatchTeamRatingTable.store

src/main/java/core/db/MatchTeamRatingTable.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/java/module/youth/YouthTrainingContext.java
=> Youth potential tuning

src/main/java/module/youth/YouthPlayer.java
=> fix npe bug in YouthPlayer.calcMaxSkills17

src/main/java/module/youth/YouthTrainingTableEntry.java, src/main/java/module/youth/YouthTrainingType.java
=> fix language strings in youth training table combo box

src/main/resources/release_notes.md
=> #779 release_notes.md

docs/README.md, src/main/java/module/training/ui/TrainingPanel.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthTrainingContext.java
colors all selected rows in training tables
=> Fix training panel selection color

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthTrainingContext.java
=> YouthPlayer.calcMaxSkills17 fix player with no max value

src/main/java/core/file/xml/XMLMatchdetailsParser.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/module/lineup/substitution/SubstitutionEditView.java
=> #1264 SubstitutionEditView.addListeners call ratingRecalc

src/main/java/module/lineup/Lineup.java, src/main/java/module/lineup/LineupSettingsPanel.java, src/main/java/module/lineup/lineup/LineupPositionsPanel.java, src/main/java/module/lineup/lineup/MatchAndLineupSelectionPanel.java, src/main/java/module/lineup/ratings/LineupRatingPanel.java, src/main/java/module/lineup/ratings/MinuteTogglerPanel.java, src/main/resources/sprache/English.properties
=> #1266 fix LineupSettingsPanel.itemStateChanged

build.gradle, docs/latestbeta.html, docs/lateststable.html
=> release stable HO5

build.gradle
=> fix build.gradle

src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/resources/release_notes.md
=> #1282 fix income spectators in ConvertXml2Hrf.createEconomy

src/main/java/module/lineup/LineupSettingsPanel.java, src/main/java/module/lineup/ratings/LineupRatingPanel.java
=> #1267 lineup layout

src/main/java/core/db/MatchTeamRatingTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/resources/release_notes.md
- fixes issues
- #1282 
- #1293 
=> #1293 rebased

src/main/java/core/db/TeamsLogoTable.java, src/main/resources/release_notes.md
=> #1300 fix TeamsLogoTable.storeTeamLogoInfo

src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLEconomyParser.java
- fixes issue #1301 (WIP)
temporary incomes are added to "Sonstiges"
=> #1301 economy fix temporary income

src/main/java/core/model/HOModel.java, src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/module/lineup/LineupPanel.java, src/main/java/module/lineup/LineupSettingsPanel.java, src/main/java/module/lineup/lineup/MatchAndLineupSelectionPanel.java, src/main/resources/release_notes.md
=> #1281 rebased

src/main/java/core/util/HTDatetime.java, src/main/java/module/teamAnalyzer/ui/controller/RecapListSelectionListener.java
=> #1267 fix date error in RecapListSelectionListener.valueChanged

src/main/java/module/lineup/LineupDatabasePanel.java, src/main/java/module/teamAnalyzer/manager/TeamManager.java, src/main/java/module/teamAnalyzer/vo/Team.java
=> #1267 fix cup match icons

src/main/java/module/lineup/substitution/SubstitutionOverview.java, src/main/resources/release_notes.md
=> #1039 SubstitutionOverview order substitutions of the same minute

src/main/java/module/lineup/Lineup.java
=> #1267 lineup store penalty takers

src/main/java/core/model/enums/MatchType.java, src/main/java/core/model/match/IMatchType.java, src/main/java/module/lineup/lineup/MatchAndLineupSelectionPanel.java, src/main/java/module/lineup/lineup/MatchBanner.java
=> #1267 fix MatchAndLineupSelectionPanel selection combo box

src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/resources/release_notes.md
=> #1301 fix ConvertXml2Hrf.createEconomy LastWeeksTotal

.github/workflows/release-dev.yml, .idea/compiler.xml, .idea/misc.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/core/db/backup/HOZip.java, utils/buildResources/HO.install4j
=> 1305 java 17 upgrade

.github/workflows/release-dev.yml
=> java 17 install4j download url

build.gradle
=> Java17 deb

.github/workflows/release-dev.yml
=> java 17 install4j debug

src/main/java/core/db/frontend/HighlightingKeyListener.java, src/main/java/core/db/frontend/TablesDialog.java, src/main/java/core/epv/EPVCalculator.java, src/main/java/core/prediction/MatchResultTable.java, src/main/java/core/prediction/MatchScoreDiffTable.java, src/main/java/core/prediction/MatchScoreTable.java, src/main/java/module/playeranalysis/SpielerPositionTable.java, src/main/java/module/playeranalysis/skillCompare/PlayerTableModel.java, src/main/java/module/transfer/history/PlayerTransferTableModel.java, src/main/java/module/transfer/history/TransferTableModel.java, src/main/java/module/transfer/scout/PlayerConverter.java, src/main/java/module/transfer/transfertype/TransferTypeTableModel.java, src/main/java/module/transfer/ui/layout/TableLayoutConstraints.java, src/main/java/tool/hrfExplorer/HrfDbDetails.java, src/main/java/tool/hrfExplorer/HrfDetails.java, src/main/java/tool/hrfExplorer/HrfExplorer.java, src/main/java/tool/hrfExplorer/HrfFileDetails.java, src/main/java/tool/updater/TableEditor.java
=> remove warnings

src/main/java/module/ifa/RightPanel.java, src/main/java/module/lineup/substitution/SubstitutionDataProvider.java, src/main/java/module/nthrf/NtPlayersParser.java, src/main/java/module/playeranalysis/skillCompare/MyTableCellRenderer.java, src/main/java/module/statistics/ArenaStatistikTable.java, src/main/java/module/teamAnalyzer/ui/NumberTextField.java, src/main/java/module/teamOfTheWeek/gui/TeamOfTheWeekPanel.java, src/main/java/module/training/ui/AnalyzerPanel.java, src/main/java/module/tsforecast/ForecastCurve.java, src/main/java/tool/hrfExplorer/HrfExplorer.java
=> remove more warnings

src/main/java/core/db/AbstractTable.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/MatchLineupTeamTable.java, src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/module/teamAnalyzer/report/TeamReport.java
fix npe in training calculation
=> fix training calculation

build.gradle
=> debug build.gradle

.idea/misc.xml, src/main/java/module/nthrf/NtTeamDetails.java, src/main/java/module/nthrf/NthrfConvertXml2Hrf.java, src/main/resources/release_notes.md, src/test/java/module/nthrf/NtTeamTest.java
- fixes issue #1305 
- [x ] have been updated
=> #1305 fix nt download parse errors

src/main/java/core/db/NtTeamTable.java, src/main/java/module/nthrf/NtTeamDetails.java, src/main/java/module/nthrf/NthrfConvertXml2Hrf.java
=> #1305xp523

src/main/java/core/db/NtTeamTable.java, src/main/java/core/file/xml/XMLManager.java, src/main/java/module/nthrf/NthrfConvertXml2Hrf.java, src/main/java/module/training/ui/model/TrainingModel.java, src/test/java/core/util/HTDatetimeTest.java
=> #1305sqlescapes

build.gradle
=> stable HO5.1 release

.github/workflows/release-dev.yml, build.gradle
=> Debug install4 j

.github/workflows/release-dev.yml
=> install4j 9 debug dev

docs/README.md
=> readme stable ho5.1

src/main/java/core/db/BasicsTable.java, src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/EconomyTable.java, src/main/java/core/db/HRFTable.java, src/main/java/core/db/MatchHighlightsTable.java, src/main/java/core/db/MatchLineupPlayerTable.java, src/main/java/core/db/SpielerNotizenTable.java, src/main/java/core/db/TournamentDetailsTable.java, src/main/java/core/db/VereinTable.java, src/main/java/core/db/XtraDataTable.java, src/main/resources/release_notes.md
=> #958 reduce database disk space usage

build.gradle
=> debug gradle create changelog

src/main/java/core/training/FutureTrainingManager.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/core/util/HTDatetimeBase.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/main/java/module/training/ui/model/TrainingModel.java
It also reverts back to Europe/Stockholm in case no default Zone ID can be computed at all.  This will be helpful in troubleshooting issue #1296 by improving logging.
Cf. above.
=> Add extra logging, and add extra null checks.

src/main/java/module/lineup/lineup/MatchAndLineupSelectionPanel.java
=> store lineup of uploaded match orders

src/main/java/core/db/DBManager.java, src/main/java/core/gui/model/PlayerAnalysisModel.java, src/main/java/core/gui/model/PlayerMatchCBItem.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/enums/MatchType.java, src/main/java/core/model/match/IMatchType.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/resources/sprache/English.properties
=> continue work on playerdetails

build.gradle
=> HO5.2 stable

docs/README.md, src/main/resources/changelog.md
=> HO5.2 stable release

src/main/java/core/db/SpielerTable.java, src/main/java/core/db/TransferTable.java, src/main/java/core/model/player/Player.java, src/main/java/core/rating/RatingPredictionManager.java, src/main/java/core/specialevents/SpecialEventsPredictionManager.java, src/main/java/module/lineup/Lineup.java, src/main/java/module/lineup/LineupSettingsPanel.java, src/main/java/module/opponentspy/OppPlayerSkillEstimator.java, src/main/java/module/playerOverview/SpielerTrainingsSimulatorPanel.java, src/main/java/module/playeranalysis/skillCompare/Player.java, src/main/java/module/transfer/scout/MiniScoutDialog.java, src/main/java/module/transfer/scout/TransferEingabePanel.java, src/main/java/module/transfer/scout/TransferTableModel.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #682 man marking effect on ratings

src/main/java/core/gui/HOMainFrame.java, src/main/java/core/util/HODateTime.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/java/module/playerOverview/SpielerUebersichtsPanel.java, src/main/resources/release_notes.md, src/test/java/core/util/HODateTimeTest.java
=> #1380 fix player overview selection sync

src/main/java/core/util/HODateTime.java, src/main/resources/release_notes.md
provide some docu of proposed HODateTime class
=> #1380 HODateTime docu

src/main/resources/release_notes.md
=> #1349 release_notes.md

src/main/java/core/model/HOModel.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java
=> #1392 HOModel.getTrainingWeeksSincePreviousDownload

src/main/java/core/net/DownloadDialog.java
=> Fix NPE when downloading data from HT

src/main/resources/release_notes.md
=> Update release notes

src/main/java/core/net/MyConnector.java
=> fix match archive download

src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/resources/release_notes.md
=> Fix db manager load matches

src/main/java/core/db/TrainingsTable.java, src/main/java/core/model/HOModel.java, src/main/java/core/training/TrainingWeekManager.java, src/main/resources/release_notes.md
fix calc subskill
save new training before loading training weeks
=> Calc subskills

src/main/java/core/HO.java, src/main/java/core/db/TransferTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/TeamSelectionDialog.java, src/main/java/core/gui/comp/table/TableSorter.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/HOModel.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/module/lineup/lineup/MatchAndLineupSelectionPanel.java, src/main/resources/release_notes.md
=> #1415 enable more than three teams

src/main/java/core/db/SpielplanTable.java, src/main/java/core/db/TournamentDetailsTable.java
=> #1413 fix date store errors

.github/workflows/release-dev.yml, src/main/java/core/gui/theme/ImageUtilities.java, src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/module/youth/YouthSkillInfoEditor.java, src/main/java/module/youth/YouthTableSorter.java, src/main/resources/release_notes.md
=> #1418youth skill chart

src/main/java/core/db/XtraDataTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/gui/HOMainFrame.java, src/main/java/core/gui/InfoPanel.java, src/main/java/core/gui/comp/table/TableSorter.java, src/main/java/core/gui/theme/ThemeManager.java, src/main/java/core/model/HOVerwaltung.java, src/main/java/core/model/match/Matchdetails.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/net/OnlineWorker.java, src/main/java/core/net/login/ProxyDialog.java, src/main/java/core/option/OptionenDialog.java, src/main/java/core/prediction/MatchEnginePanel.java, src/main/java/module/ifa/PluginIfaUtils.java, src/main/java/module/lineup/assistant/LineupAssistantPanel.java, src/main/java/module/matches/MatchesTable.java, src/main/java/module/transfer/history/HistoryPane.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/tool/export/CsvPlayerExport.java, src/main/java/tool/export/XMLExporter.java, src/main/java/tool/updater/UpdateController.java
=> #1413 progress display over the entire download process

src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchLineupTeamTable.java, src/main/java/module/lineup/LineupDatabasePanel.java
=> #1422 LineupDatabasePanel.deleteTemplate

src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchesKurzInfoTable.java, src/main/java/core/db/SpielplanTable.java, src/main/java/core/file/xml/XMLMatchArchivParser.java, src/main/java/core/model/match/MatchKurzInfo.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/net/LigaAuswahlDialog.java, src/main/java/core/net/MyConnector.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/matches/MatchesModel.java, src/main/java/module/series/SeriesPanel.java, src/main/java/module/teamOfTheWeek/gui/TeamOfTheWeekPanel.java, src/main/resources/release_notes.md
=> #1413 fix download of old league data

src/main/java/core/db/DBManager.java, src/main/java/core/db/HRFTable.java, src/main/java/core/model/HOModel.java, src/main/java/core/training/TrainingManager.java, src/main/java/module/playerOverview/PlayerSubskillOffsetDialog.java, src/main/java/module/training/ui/model/AbstractTrainingsTableModel.java, src/main/java/tool/keepertool/ResultPanel.java, src/main/resources/release_notes.md
=> Fix save training

src/main/java/core/gui/comp/table/TableSorter.java, src/main/java/core/model/misc/Basics.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/util/HODateTime.java
=> #1413 disable load of old fixtures in initial download

src/main/java/core/model/UserParameter.java, src/main/java/core/net/DownloadDialog.java, src/main/resources/release_notes.md
=> #1413 fix bug when downloading fixtures for the very first time

src/main/java/core/training/TrainingWeekManager.java
=> #1437 fix TrainingWeekManager.createTPWfromDBentries

src/main/java/module/training/ui/TrainingRecapTable.java, src/main/resources/release_notes.md
=> #1439 fix TrainingRecapTable.getColumns

src/main/java/core/db/DBUpdater.java, src/main/java/core/db/SpielerTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLPlayersParser.java, src/main/java/core/gui/model/PlayerAnalysisModel.java, src/main/java/core/gui/model/PlayerOverviewModel.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/player/Player.java, src/main/java/core/model/player/PlayerCategory.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1441 players' category, statement and owner notes

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java
=> #1445 dbversion 601

src/main/java/core/db/DBManager.java
=> #1445 dev instance stores previousDBVersion

src/main/java/core/util/HODateTime.java
=> #1433 HODateTime.fromHT accept date only

src/main/java/core/training/FuturePlayerTraining.java
=> #1456 fix npe in FuturePlayerTraining.cut

src/main/java/core/model/match/MatchLineupTeam.java
=> #1458 MatchLineupTeam.getPlayerFieldPositionAtMinute

src/main/java/core/gui/model/UserColumnFactory.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1454 UserColumnFactory width of shirt number column

src/main/java/core/gui/comp/table/UserColumn.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/option/UserColumnsPanel.java, src/main/resources/release_notes.md
=> #1454 makes shirt number column display status editable

src/main/java/core/db/BasicsTable.java, src/main/java/core/db/DBManager.java, src/main/java/core/db/SpielerTable.java, src/main/java/core/util/HODateTime.java, src/main/java/module/playerOverview/SpielerTrainingsVergleichsPanel.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1452 training week

src/main/java/core/model/UserParameter.java, src/main/resources/release_notes.md
=> #1468 adjust initial slider positions

src/main/java/core/db/TrainingsTable.java, src/main/java/module/misc/FinancePanel.java, src/main/java/module/misc/MiscPanel.java
=> #1469 fix sql error in TrainingsTable.saveTraining

src/main/java/module/series/MatchDayPanel.java, src/main/resources/release_notes.md
=> #1461 fix progress bar completion

src/main/java/core/db/HRFTable.java
=> #1481 fix HRFTable.saveHRF

src/main/java/tool/dbcleanup/DBCleanupTool.java
=> #1466 fix DBCleanupTool.cleanupHRFs

src/main/java/module/training/TrainingModulePanel.java
=> #1468 adjust training panel split sizes

src/main/java/core/training/FuturePlayerTraining.java
=> #1486 fix FuturePlayerTraining.cut

src/main/java/core/util/HODateTime.java, src/main/java/module/transfer/test/Calc.java, src/main/java/module/tsforecast/ConfidenceCurve.java, src/main/java/module/tsforecast/ForecastCurve.java, src/main/java/module/tsforecast/HistoryCurve.java, src/main/java/module/tsforecast/TSForecast.java, src/main/java/module/tsforecast/TSPanel.java, src/main/java/module/tsforecast/TrainerCurve.java
- fixes bugs in ts forecast module
=> debug TSForecast

src/main/java/core/training/FuturePlayerTraining.java
- fixes issue #_npe in FuturePlayerTraining.cut (again)_  
=> fix npe in FuturePlayerTraining.cut

src/main/java/core/gui/comp/entry/SmilieEntry.java
=> #1477 fix npe in SmilieEntry.compareTo

build.gradle
=> start HO6.0 beta

build.gradle, src/main/resources/changelog.md, src/main/resources/release_notes.md
update change log and start version HO7.0
=> Init ho7 development

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java
=> init db version 700

src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/core/model/match/StyleOfPlay.java, src/main/java/core/model/player/Player.java
=> #1519 fix MatchLineupTeam.examineSubstitution

build.gradle, src/main/java/core/gui/HOMainFrame.java, src/main/java/core/model/HOVerwaltung.java, src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/core/model/match/StyleOfPlay.java, src/main/java/core/model/player/Player.java, src/main/java/core/training/TrainingWeekManager.java
merge changes on release/6 branch
=> Merge release6

src/main/resources/sprache/English.properties
=> #1525 ls.section.reuse added to English.properties

build.gradle
=> #1530master

src/main/java/core/db/DBUpdater.java
changed log level of db update
=> #1524 DBUpdater change log level (WIP)

src/main/java/tool/updater/UpdateController.java
=> #1545 fix UpdateController.get_HO_zip_download_url (fetch jre-zips)

src/main/resources/release_notes.md
=> release_notes.md translators

src/main/java/module/lineup/lineup/MatchBanner.java
=> #1552 MatchBanner.refresh change log level from error to info

src/main/java/module/matches/MatchReportPanel.java, src/main/resources/release_notes.md
=> Match report panel

src/main/java/module/statistics/MatchesStatisticsPanel.java
=> #1561 fix date in MatchesStatisticsPanel

src/main/java/core/db/SpielerTable.java
=> #1524 fix SpielerTable.initColumns

src/main/java/module/matches/MatchesModel.java, src/main/java/module/matches/MatchesPanel.java, src/main/java/module/teamAnalyzer/ui/FilterPanel.java
=> #1553 reset download progress bar when finished

src/main/java/core/db/StatisticQuery.java, src/main/java/core/util/chart/HODoublePieChart.java, src/main/resources/release_notes.md
=> #1561 StatisticQuery fix time axis

src/main/java/module/lineup/assistant/LineupAssistantPanel.java
=> #1571 fix npe in LineupAssistantPanel.actionPerformed

build.gradle, src/main/java/core/util/chart/HODoublePieChart.java, src/main/java/core/util/chart/HOLinesChart.java
update to latest version of xchart lib
=> xchart 3.8.1

src/main/java/module/youth/YouthPlayer.java, src/main/resources/release_notes.md
=> #1578 YouthPlayer.getCanBePromotedInAtDate format duration

src/main/java/core/gui/Credits.java, src/main/java/core/gui/comp/HyperLinkLabel.java, src/main/java/core/model/player/Player.java, src/main/java/core/util/HOLogger.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1576 About dialog shows database and logs folder

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/resources/release_notes.md
=> #1580 database update (602) removes corrupts hrf table entries

src/main/java/core/db/DBUpdater.java
=> DBUpdater handle intermediate db version 602

utils/buildResources/HO.install4j
- fixes issue 
Ok I think I somehow passed the installation step but when I try running the application it says "You can’t open the application “Hattrick Organizer” because PowerPC applications are no longer supported." and I am stuck there..
=> install4j mac universal architecture

build.gradle
=> #1580 hsqldb:2.5.0

src/main/java/core/gui/model/UserColumnFactory.java, src/main/resources/release_notes.md
=> #1598 UserColumnFactory fix sorting of hatstats columns

src/main/java/core/model/match/Matchdetails.java
=> #1603 fix npe in Matchdetails.downloadHighlightsIfMissing

build.gradle, src/main/java/core/model/HOVerwaltung.java
=> #1607 build dependencies language files

src/main/resources/release_notes.md
=> release_notes.md translators update

src/main/java/core/file/hrf/HRFImport.java, src/main/java/core/file/hrf/HRFStringParser.java, src/main/java/core/file/xml/XMLPlayersParser.java, src/main/java/core/model/player/Player.java, src/main/java/core/training/TrainingPoints.java
=> #1615 fix error handling of hrf import

src/main/java/core/model/player/Player.java
=> #1542 logs with semicolon

build.gradle, src/main/resources/release_notes.md
=> Release ho6

build.gradle, src/main/java/core/file/xml/XMLMatchLineupParser.java, src/main/java/core/model/match/MatchLineupTeam.java, src/main/resources/release_notes.md
=> #1633 fix handling of replacement of injured keeper by field player

build.gradle, src/main/java/core/prediction/TeamRatingPanel.java, src/main/resources/release_notes.md
=> fix team analyzer simulation out of bounds error

src/main/resources/release_notes.md
=> #1630 release_notes.md

src/main/java/core/gui/comp/table/TableSorter.java, src/main/java/module/playeranalysis/skillCompare/TableSorter.java, src/main/java/module/transfer/ui/sorter/MouseHandler.java, src/main/java/module/youth/YouthTableSorter.java, src/main/resources/release_notes.md
=> #1645 fix sorting exception of involid column indexes

src/main/java/core/model/misc/Basics.java, src/main/resources/release_notes.md
=> #1651 fix season offset when upgrading from HO3

src/main/java/core/prediction/TeamRatingPanel.java, src/main/java/module/teamAnalyzer/ui/RatingUtil.java, src/main/resources/release_notes.md
=> #1655 fix wrong rating values in TeamRatingPanel.addLine

src/main/java/core/HOLauncher.java, src/main/java/core/prediction/TeamRatingPanel.java, src/main/java/module/teamAnalyzer/ui/RatingUtil.java, src/main/resources/changelog.md
- fixes issue #1655 and others
=> Merge ho6.1

build.gradle, src/main/resources/release_notes.md
=> release stable 6.1

docs/README.md
=> release stable 6.1 README.md

docs/README.md
=> Release ho6.1 fix readme

src/main/java/core/db/DBManager.java, src/main/java/core/training/TrainingWeekManager.java, src/main/java/module/training/ui/model/TrainingModel.java
=> #1668 future training fix of daylight saving time error

src/main/java/core/db/DBConfigUpdater.java, src/main/java/core/db/DBManager.java, src/main/java/core/db/MatchLineupTeamTable.java, src/main/java/core/db/SpielerSkillupTable.java, src/main/java/core/db/TransferTable.java, src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/core/model/player/Player.java, src/main/java/core/rating/RatingPredictionManager.java, src/main/java/module/training/ui/comp/FutureTrainingsEditionPanel.java, src/main/java/module/training/ui/model/TrainingModel.java, src/main/java/module/transfer/PlayerTransfer.java
=> #1674 tune refreshing panels

build.gradle, src/main/java/core/model/player/Player.java
=> #1674 fix past skill ups

src/main/java/core/db/YouthTrainingTable.java
=> #1674 fix error in YouthTrainingTable

src/main/java/core/db/UserColumnsTable.java
- fixes issue #1681 the stack overflow
=> #1681 fix stack overflow in UserColumnsTable

src/main/java/core/util/HODateTime.java
=> #1668 fix HODateTime.plusDaysAtSameLocalTime daylight saving error

src/main/java/core/db/StatisticQuery.java, src/main/java/core/model/match/MatchLineupPosition.java, src/main/java/core/util/chart/HOLinesChart.java, src/main/java/module/statistics/PlayerStatisticsPanel.java
=> #1685 fix Arena statistics

src/main/java/module/ifa/model/IfaModel.java, src/main/java/module/training/ui/renderer/TrainingRecapRenderer.java
=> #1684 fix error in TrainingRecapRenderer

src/main/java/core/HOLauncher.java
=> #1681 update excludes .install4j folder from deletion

build.gradle
=> #1691 remove poeditor dependency (temporarily)

build.gradle
=> #1691debug

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/core/net/MyConnector.java
=> Upgrade libs

build.gradle
- fixes issue #1691 (poeditor restored HO translation project)
=> #1691 restore poeditor plugin

src/main/java/core/db/DBManager.java, src/main/java/core/db/PaarungTable.java, src/main/resources/sprache/Legacy/Spanish(AR).properties
=> #1701 fix DBManager.getSpielplan (load fixtures too)

src/main/java/module/statistics/PlayerStatisticsPanel.java, src/main/resources/release_notes.md
=> #1705 PlayerStatisticsPanel filters former players

src/main/java/core/model/player/Player.java, src/main/java/core/util/HODateTime.java, src/main/java/module/transfer/history/PlayerDetailPanel.java, src/main/java/module/transfer/history/PlayerTransferTableModel.java, src/main/java/module/transfer/history/TeamTransfersPane.java, src/main/java/module/transfer/history/TransferTableModel.java, src/main/resources/release_notes.md
=> #1659 TransferTableModel add player age column

src/main/java/core/db/MatchLineupTeamTable.java, src/main/java/core/db/SpielerTable.java, src/main/java/core/model/player/PlayerCategory.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/core/training/type/PlaymakingWeeklyTraining.java
=> #1661 PlaymakingWeeklyTraining fix osmosis training of goalkeeper

src/main/java/core/db/AbstractTable.java, src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java, src/main/java/core/db/IfaMatchTable.java, src/main/java/core/db/LigaTable.java, src/main/java/core/db/MatchSubstitutionTable.java, src/main/java/core/db/SpielerNotizenTable.java, src/main/java/core/db/TeamsLogoTable.java, src/main/java/core/db/TransferTable.java, src/main/java/core/db/user/BaseUser.java, src/main/java/core/db/user/User.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/gui/model/PlayerColumn.java, src/main/java/core/gui/model/PlayerOverviewModel.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/gui/theme/ThemeManager.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/transfer/history/TransferTableModel.java
=> #1710 fix npe in initial download

.github/workflows/release-dev.yml
=> #1712 use actions/checkout@v3

.github/workflows/release-dev.yml, src/main/java/core/HO.java
=> #1716 fix workflow

src/main/java/module/transfer/history/PlayerTransferTableModel.java, src/main/java/module/transfer/history/TransferTableModel.java
=> #1659 fix npe in PlayerTransferTableModel.getValueAt

src/main/java/core/db/SpielerNotizenTable.java, src/main/java/core/model/player/Player.java
=> #1721 fix bug in storing player notes

.github/workflows/release-dev.yml
=> #1712 christian-draeger/read-properties@1.1.0

.github/workflows/release-dev.yml
=> #1712set output deprecated debug

.github/workflows/release-dev.yml
=> #1712set output deprecated debug2

.github/workflows/release-dev.yml
=> #1712set output deprecated debug3

.github/workflows/release-dev.yml
=> #1712set output deprecated debug4

.github/workflows/release-dev.yml
=> #1712node12

src/main/java/core/db/UserColumnsTable.java, src/main/java/core/gui/comp/table/HOTableModel.java, src/main/java/core/gui/model/PlayerAnalysisModel.java, src/main/java/core/gui/model/PlayerOverviewModel.java, src/main/java/module/lineup/LineupTableModel.java, src/main/java/module/youth/YouthPlayerDetailsTableModel.java
=> #1749 fix bug in settings of disabled columns

.github/pull_request_template.md
This updates the PR template to give clarity as to what file needs to be updated upon submitting a PR.
=> Update PR template for clarity.

src/main/java/core/db/DBManager.java, src/main/java/core/model/misc/Basics.java, src/main/java/core/model/player/Player.java, src/main/java/core/util/BrowserLauncher.java, src/main/java/core/util/DateTimeUtils.java, src/main/java/core/util/HODateTime.java, src/main/java/core/util/HOLogger.java, src/main/java/core/util/HelperWrapper.java, src/main/java/core/util/StringUtils.java, src/main/java/core/util/XMLUtils.java, src/main/java/module/ifa/PluginIfaUtils.java, src/main/java/module/teamAnalyzer/ui/MatchComboBoxRenderer.java
Just a few minor cleanups to clarify a few things.  Also replaced in a few instances `StringBuffer` with `StringBuilder`.
=> Minor cleanups

src/main/java/core/db/UserColumnsTable.java, src/main/java/core/gui/comp/table/HOTableModel.java, src/main/java/core/gui/comp/table/UserColumn.java, src/main/java/core/gui/model/PlayerOverviewModel.java, src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/option/OptionManager.java, src/main/java/core/option/OptionenDialog.java, src/main/java/core/option/TrainingPreferencesPanel.java, src/main/java/core/option/UserColumnsPanel.java, src/main/java/module/lineup/LineupPlayersTable.java, src/main/java/module/lineup/LineupTableModel.java, src/main/java/module/playerOverview/PlayerOverviewTable.java
Make Name and ID non-editable (it cannot be removed from players' list), and make sure that if no column is available in the list that all columns are visible, except for ID.
Cf. above
=> Fix ArrayIndexOutofBound

src/main/java/core/db/IfaMatchTable.java, src/main/java/core/db/WorldDetailsTable.java, src/main/resources/release_notes.md
=> #1622 fix init error of world details table

src/main/java/core/gui/model/UserColumnFactory.java, src/main/resources/release_notes.md
=> #1780 fix npe in player table

build.gradle, src/main/java/core/rating/RatingPredictionManager.java, src/main/resources/release_notes.md
=> start HO7 beta

.github/workflows/release-dev.yml, src/main/java/module/series/FormLabel.java, src/main/java/module/tsforecast/ConfidenceCurve.java, src/main/java/module/tsforecast/HistoryCurve.java, src/main/resources/release_notes.md
=> #1793 fix order of last 5 matches in league table

src/main/java/module/lineup/lineup/LineupPositionsPanel.java, src/main/resources/release_notes.md
=> #1795 fix npe in LineupPositionsPanel

src/main/java/core/training/TrainingManager.java, src/main/java/module/training/ui/OutputPanel.java, src/main/java/module/training/ui/TrainingDevelopmentPanel.java, src/main/java/module/training/ui/TrainingPredictionPanel.java, src/main/java/module/training/ui/TrainingRecapTable.java, src/main/java/module/training/ui/model/TrainingModel.java, src/main/resources/release_notes.md
=> #1798 fix TrainingDevelopmentPanel.update

src/main/java/core/util/HOLogger.java, src/main/resources/release_notes.md
=> #1800 fix HOLogger

src/main/java/core/gui/theme/BaseTheme.java, src/main/java/core/model/UserParameter.java, src/main/java/core/model/player/PlayerAvatar.java, src/main/java/core/net/DownloadDialog.java, src/main/java/core/option/GeneralSettingsPanel.java, src/main/java/core/option/OptionenDialog.java, src/main/java/core/option/SliderPanel.java, src/main/java/core/option/TrainingPreferencesPanel.java, src/main/java/core/util/Helper.java, src/main/java/module/series/SeriesTablePanel.java, src/main/java/module/statistics/TeamStatisticsPanel.java, src/main/java/module/teamAnalyzer/ui/PlayerPanel.java, src/main/java/module/teamAnalyzer/ui/SpecialEventsPanel.java, src/main/java/module/teamAnalyzer/ui/TeamAnalyzerPanel.java, src/main/java/module/teamAnalyzer/ui/TeamPanel.java, src/main/java/module/teamAnalyzer/ui/lineup/LineupStylePanel.java, src/main/java/module/teamAnalyzer/ui/lineup/MixedLineupPanel.java, src/main/java/module/teamAnalyzer/ui/lineup/StandardLineupPanel.java, src/main/resources/release_notes.md
=> #1805 grid layout

src/main/java/core/db/DBManager.java, src/main/java/core/db/DBUpdater.java
=> #1817 fix db update (updateDBv701)

src/main/java/core/db/DBManager.java
=> #1821 fix DBManager.deleteMatch

src/main/java/core/db/NtTeamTable.java
=> #1827 fix NtTeamTable.loadNTTeam

src/main/java/core/db/LigaTable.java, src/main/java/core/file/hrf/HRFStringParser.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/model/misc/Basics.java, src/main/java/core/model/player/Player.java, src/main/resources/release_notes.md
=> #1829 fix import of hrf file from portal tracker

src/main/java/core/gui/comp/table/TableSorter.java
=> #1729 fix TableSorter.getValueAt array out of bounds exception

src/main/java/module/transfer/scout/PlayerConverter.java, src/main/java/module/transfer/scout/TransferEingabePanel.java, src/main/resources/release_notes.md
=> #1841 fix transfer scout player data scanner

src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/player/Player.java
=> fix last match position if undefined

src/main/java/core/net/MyConnector.java, src/main/java/core/net/OnlineWorker.java, src/main/java/module/lineup/Lineup.java
=> fix bug in download lineup

build.gradle, docs/latestbeta.html, docs/lateststable.html, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> release HO 7.0

docs/README.md, docs/latest.html, docs/lateststable.html
=> Continue release

src/main/java/module/lineup/substitution/model/GoalDiffCriteria.java, src/main/java/module/lineup/substitution/model/RedCardCriteria.java
=> #1861 fix exception in GoalDiffCriteria

.github/workflows/release-dev.yml, src/main/java/core/file/hrf/HRFStringBuilder.java, src/main/java/core/gui/DebugMode.java, src/main/java/core/net/MyConnector.java, src/main/java/core/training/TrainingPreviewPlayers.java, src/main/java/module/lineup/substitution/LanguageStringLookup.java, src/main/java/module/lineup/substitution/SubstitutionDataProvider.java, src/main/java/module/lineup/substitution/model/GoalDiffCriteria.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1881 debug worlflow

build.gradle, src/main/resources/release_notes.md
=> Release ho7.1

build.gradle, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLPlayersParser.java, src/main/java/core/model/player/Player.java, src/main/java/core/net/MyConnector.java, src/main/java/module/training/ui/model/TrainingModel.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #1889 download new trainer info from player details

build.gradle, src/main/resources/release_notes.md
=> stable 7.2

src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/resources/release_notes.md
=> #1901 PlayerDetailsPanel reset homegrown icon

.github/workflows/release-dev.yml
=> release-dev INSTALL4J_HOME

docs/README.md, docs/contributing.md, docs/installing_ho.rst, docs/release_notes(stable).md, src/main/java/core/gui/Credits.java, src/main/java/core/gui/HOMainFrame.java, src/main/java/core/net/MyConnector.java, src/main/java/core/training/WeeklyTrainingType.java, src/main/java/core/util/Updater.java, src/main/java/module/pluginFeedback/FeedbackPanel.java, src/main/java/module/transfer/scout/MiniScoutDialog.java, src/main/java/module/transfer/scout/TransferEingabePanel.java, src/main/java/tool/updater/UpdateController.java, src/main/resources/changelog.md, src/main/resources/release_notes.md, utils/buildResources/HO.install4j, utils/buildResources/changelog.html, utils/pythonScripts/update_foxtrick_ho_json.py
- issue #1736 (replace old urls)
=> https://github.com/ho-dev/HattrickOrganizer

src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/core/model/player/Player.java, src/main/resources/release_notes.md
=> #1913 fix Player.getMotherclubId download recursion

src/main/java/core/file/xml/ConvertXml2Hrf.java
=> fix merge errpr

src/main/java/core/gui/theme/ThemeManager.java, src/main/java/core/model/player/PlayerAvatar.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1815 download player avatar

src/main/java/module/training/ui/OutputPanel.java, src/main/resources/release_notes.md
=> #1936 fix scrolling of training table

src/main/java/core/model/UserParameter.java, src/main/java/core/prediction/MatchPredictionDialog.java, src/main/resources/release_notes.md, src/test/java/module/nthrf/NtTeamTest.java
=> #1898 restore size of MatchPredictionDialog

src/main/java/core/constants/player/PlayerAggressiveness.java, src/main/java/core/constants/player/PlayerAgreeability.java, src/main/java/core/constants/player/PlayerHonesty.java, src/main/java/core/constants/player/PlayerSpeciality.java, src/main/java/core/file/hrf/HRFStringBuilder.java, src/main/java/core/file/hrf/HRFStringParser.java, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLStaffParser.java, src/main/java/core/model/HOProperties.java, src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/core/model/player/Player.java
=> #1948 npe on downloading new trainer data

build.gradle, src/main/resources/release_notes.md, src/test/java/core/util/KotlinBehaviourTest.kt
Also add a unit test acting as a smoke test, and experimenting with some Kotlin features.
Cf. above
=> Add Kotlin support to project.

.idea/codeStyles/Project.xml, src/main/java/core/rating/RatingPredictionModel.java, src/main/java/module/youth/YouthTraining.java, src/main/resources/release_notes.md
=> #1950 increase effect of youth friendly training

src/main/java/core/file/xml/ConvertXml2Hrf.java
=> #1959 fix ConvertXml2Hrf.createHrf

src/main/java/core/db/MatchDetailsTable.java, src/main/java/core/file/xml/XMLManager.java, src/main/java/core/file/xml/XMLPlayersParser.java, src/main/java/module/transfer/PlayerTransfer.java
=> #1979 fix XMLPlayersParser.youthplayerSkills2Hash

build.gradle, src/main/resources/release_notes.md
=> #1967 move prediction groovy implementations to prediction directory

src/main/java/core/constants/player/PlayerSkill.java, src/main/java/core/file/hrf/HRFStringBuilder.java, src/main/java/core/file/xml/XMLPlayersParser.java, src/main/java/module/youth/YouthPlayer.java
- fixes bug in youth player download
=> fix youth player skill download

src/main/java/core/db/DBManager.java, src/main/java/core/db/SpielerTable.java, src/main/java/core/file/xml/XMLPlayersParser.java, src/main/java/core/model/player/Player.java, src/main/java/core/model/player/SkillChange.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/java/module/transfer/history/PlayerDetailPanel.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #741 player's total cost of ownership

src/main/java/module/youth/YouthPlayerView.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1449 modify youth player view layout

src/main/java/module/youth/YouthPlayerColumn.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthPlayerView.java, src/main/java/module/youth/YouthTrainingColumn.java, src/main/java/module/youth/YouthTrainingViewTableModel.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1558 set initial youth module view layout

src/main/java/module/youth/YouthTraining.java, src/main/resources/release_notes.md
=> #1994 exact value of new youth friendly training effect

src/main/java/core/gui/HOMainFrame.java, src/main/java/core/training/TrainingManager.java, src/main/java/core/util/HODateTime.java, src/main/java/module/youth/YouthPlayerView.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #1556 Change subskill recalculation dialog display

src/test/java/core/constants/player/PlayerAbilityTest.kt
- fixes failed tests while building. See discussion https://github.com/ho-dev/HattrickOrganizer/issues/1988#issuecomment-1866663137
3. [Optional] suggested person to review this PR @wsbrenk @tychobrailleur
=> refactor Player Ability Tests expected value

src/main/java/core/db/DBUpdater.java
=> #1905 remove database table SPIELERSKILLUP

src/main/java/core/gui/comp/entry/ColorLabelEntry.java, src/main/java/core/gui/theme/ImageUtilities.java, src/main/java/core/option/OptionenDialog.java, src/main/java/module/playerOverview/SpielerTrainingsSimulatorPanel.java, src/main/java/module/playeranalysis/skillCompare/MyTableCellRenderer.java, src/main/java/module/teamAnalyzer/ui/RatingPanel.java, src/main/java/module/teamAnalyzer/ui/RosterTableRenderer.java, src/main/java/module/teamAnalyzer/ui/lineup/RatingBox.java, src/main/java/module/training/ui/AnalyzerPanel.java, src/main/java/module/training/ui/TrainingLegendPanel.java, src/main/java/module/transfer/history/PlayerDetailPanel.java, src/main/java/module/tsforecast/TSPanel.java
=> #2007 don't show change arrow if value did not change

src/main/java/module/training/ui/TrainingLegendPanel.java
=> #2023 fix npe in TrainingLegendPanel

src/main/java/core/db/FuturePlayerSkillTrainingTable.java
=> #2013 fix FuturePlayerSkillTrainingTable.storeFuturePlayerSkillTraining

.github/workflows/release-dev.yml
=> #2019 update node.js actions

src/main/java/core/db/DBManager.java, src/main/java/core/db/TrainingsTable.java, src/main/java/core/file/hrf/HRFImport.java, src/main/java/core/training/TrainingPerPlayer.java
=> #2028 fix hrf file import

src/main/java/core/db/DBManager.java
=> #2031 fix getConnectionManager

src/main/java/core/gui/theme/BaseTheme.java, src/main/java/core/gui/theme/HOColor.java, src/main/java/core/gui/theme/HOColorName.java, src/main/java/core/gui/theme/ThemeManager.java, src/main/java/core/option/ColorTableCellEditor.java, src/main/java/core/option/OptionenDialog.java, src/main/java/core/option/UserColorsPanel.java
=> #2021 fix color editing

src/main/java/core/db/DBManager.java, src/main/java/core/db/TransferTable.java, src/main/java/core/file/xml/ConvertXml2Hrf.java
=> #2031 optimize transfer downloads

.github/workflows/release-dev.yml
=> fix version of softprops/action

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/java/module/youth/YouthSkillsInfo.java, src/main/java/module/youth/YouthTrainingContext.java, src/main/resources/release_notes.md, src/main/resources/sprache/English.properties
=> #2035 future youth player development

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/java/module/youth/YouthSkillsInfo.java
=> #2035 debug Youthplayer potential calculation

src/main/java/core/gui/model/UserColumnFactory.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/resources/release_notes.md
=> #2044 fix player details display after initial download

src/main/java/module/youth/YouthPlayer.java
=> #2035 fix YouthPlayer.calcTrainingDevelopment keeper's skill limits

src/main/java/core/gui/comp/table/HOTableModel.java, src/main/java/core/gui/comp/table/TableSorter.java, src/main/java/module/lineup/LineupPlayersTable.java, src/main/java/module/playerOverview/LineupPlayersTableNameColumn.java, src/main/java/module/playerOverview/PlayerDetailsPanel.java, src/main/java/module/playerOverview/PlayerOverviewPanel.java, src/main/java/module/playerOverview/PlayerOverviewTable.java
=> #752 LineupPlayerTable uses TableModelListener instead of MouseListener

src/main/java/module/teamAnalyzer/ui/TeamInfoPanel.kt, src/main/resources/release_notes.md
=> #2055 fix slow opening of team analyzer panel

src/main/java/module/teamAnalyzer/ui/FilterPanel.java, src/main/java/tool/dbcleanup/DBCleanupDialog.kt
Finally fix properly the hanging Swing UI when downloading the matches in the Team Analyzer tab.
cf. above
=> Use SwingWorker to properly fix hanging UI.

src/main/java/module/teamAnalyzer/ui/RecapPanelTableModel.java, src/main/resources/release_notes.md
=> #2059 fix currency error in team analyzer's total salary column

src/main/java/core/rating/RatingPredictionModel.java, src/main/java/module/lineup/LineupSettingsPanel.java, src/main/java/module/lineup/ratings/LineupRatingPanel.java
=> #2074 update ratings when team spirit is changed

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthPlayerOverviewTableModel.java, src/main/resources/release_notes.md
=> #2076 sorting of youth table average column

src/main/java/module/tsforecast/TrainerCurve.java, src/main/resources/release_notes.md
=> #2078 ts forecast loads all trainer data

.github/workflows/release-dev.yml, src/main/resources/release_notes.md
=> Create `stable` tag when `tag_stable` is created.

docs/README.md, src/main/resources/release_notes.md
=> Release ho8

build.gradle
=> Select suffix in extension block, as it then becomes immutable.

src/main/java/core/model/match/MatchLineupTeam.java
=> #2097 Fix npe in MatchLineupTeam.initMinutesOfPlayersInSectors

src/main/java/core/rating/RatingCalculationCache4.java, src/main/java/core/rating/RatingPredictionModel.java, src/main/java/module/playerOverview/PlayerSubskillOffsetDialog.java, src/main/resources/changelog.md
=> #235 refresh on edit playerskills

src/main/java/core/db/MatchDetailsTable.java, src/main/java/core/net/test/ConnTest.java, src/main/java/core/specialevents/SpecialEventsPredictionManager.java, src/main/java/module/training/Skills.java, src/main/java/tool/updater/VersionInfo.java
- improve code quality of this Java project
=> refactor: reordering the modifiers to comply with the Java Language Specification

gradle.properties, src/main/resources/release_notes.md
=> Release 8.1

src/main/java/core/model/enums/DBDataSource.java, src/main/java/core/model/enums/RatingsStatistics.java, src/main/java/core/util/Languages.java, src/main/java/module/ifa/config/Config.java, src/main/java/module/lineup/substitution/plausibility/Error.java, src/main/java/module/lineup/substitution/plausibility/Uncertainty.java, src/main/java/module/specialEvents/SeasonFilterValue.java, src/main/java/module/training/TrainingType.java
- improve code quality of this Java project
=> refactor: making fields final in enum

src/main/java/core/file/xml/XMLCHPPPreParser.java, src/main/java/core/file/xml/XMLMatchLineupParser.java, src/main/java/core/gui/comp/icon/StatusIcon.java, src/main/java/core/gui/comp/table/ToolTipHeader.java, src/main/java/core/model/match/MatchTeamRating.java, src/main/java/core/module/config/ModuleConfig.java, src/main/java/core/rating/RatingPredictionConfig.java, src/main/java/core/util/StringUtils.java, src/main/java/module/ifa/PluginIfaUtils.java, src/main/java/module/ifa/gif/Gif89Encoder.java, src/main/java/module/ifa/table/IfaTableModel.java, src/main/java/module/lineup/lineup/LineupCheck.java, src/main/java/module/matches/MatchberichtEditorPanel.java, src/main/java/module/nthrf/MainPanel.java, src/main/java/module/nthrf/NthrfConvertXml2Hrf.java, src/main/java/module/nthrf/NthrfUtil.java, src/main/java/module/playeranalysis/skillCompare/TableSorter.java, src/main/java/module/series/MatchDayPanel.java, src/main/java/module/specialEvents/SpecialEventsDM.java, src/main/java/module/teamAnalyzer/manager/MatchManager.java, src/main/java/module/teamAnalyzer/manager/TeamLineupBuilder.java, src/main/java/module/teamAnalyzer/ui/component/DeletePanel.java, src/main/java/module/teamAnalyzer/ui/component/FavouriteMenu.java, src/main/java/module/transfer/scout/Player.java, src/main/java/module/youth/YouthTableSorter.java, src/main/java/tool/hrfExplorer/HrfTableModel.java
- improve code quality of this Java project
=> refactor: using '.isEmpty()' instead of '.size() == 0'

src/test/java/core/util/HODateTimeTest.java, src/test/java/module/nthrf/NtTeamTest.java, src/test/java/module/series/HattidEndPointTest.java
- removing public scope to use the recommended default visibility 'package private' to improve readability
=> refactor: remove public scope from test classes and test methods

build.gradle, src/main/java/core/file/xml/XMLArenaParser.java, src/main/java/core/util/ResourceUtils.java, src/test/java/core/file/xml/XMLArenaParserTest.java, src/test/resources/arenaDetails_noExpansion.xml, src/test/resources/arenaDetails_withExpansion.xml
- fixes issue #2126
- added tests for parsing 'arenadetails.xml'
=> [BUG] #2126: Reading the values from 'ExpandedCapacity' of XML file 'arenadetails.xml'

src/main/java/module/ifa/ImageDesignPanel.java, src/main/java/module/matches/statistics/MatchesOverviewTable.java, src/main/java/module/playeranalysis/SpielerMatchesTable.java
=> Refactor: Java 5 issues: Remove unnecessary boxing

src/main/java/module/teamAnalyzer/vo/MatchRating.java
- removing unnecessary semicolons
=> Refactor: Remove unnecessary semicolons

src/main/java/core/gui/comp/table/ToolTipHeader.java
- collapsing identical 'catch' blocks
=> Refactor: Java 7 issues: Collapse identical 'catch' blocks

src/main/java/core/module/config/ModuleConfig.java, src/main/java/core/net/test/ConnTest.java, src/main/java/core/prediction/engine/BaseActionGenerator.java
- Removing final modifier from static methods because they are always final by design
=> Refactor: Remove final modifier from static methods

src/main/java/core/gui/IRefreshable.java, src/main/java/core/gui/theme/HOBooleanName.java, src/main/java/core/model/StaffType.java, src/main/java/module/ifa/config/Config.java, src/main/java/module/lineup/substitution/plausibility/Uncertainty.java, src/main/java/module/specialEvents/SeasonFilterValue.java, src/main/java/module/transfer/ui/layout/TableLayoutConstants.java
- Refactor: Remove unnecessary modifiers
=> Refactor: Remove unnecessary modifiers

.github/workflows/release-dev.yml
=> Create another release for `stable`, along with `tag_stable` and version number

src/main/java/core/db/user/BaseUser.java, src/main/java/core/option/TrainingPreferencesPanel.java, src/main/java/module/series/promotion/ProcessAsynchronousTask.java, src/main/java/module/teamAnalyzer/ui/lineup/FormationPanel.java, src/main/java/module/transfer/ui/sorter/Directive.java, src/main/java/module/tsforecast/Curve.java, src/main/java/module/tsforecast/TrainerCurve.java, src/main/java/module/youth/YouthTableSorter.java, src/main/java/tool/injury/InjuryDetailPanel.java
Prevent that a class is exposed outside its defined visibility scope.
=> refactor: Prevent that a class is exposed outside its defined visibility scope

src/main/java/core/util/HODateTime.java, src/test/java/core/util/HODateTimeTest.java
Fixes the failing test and added test for HoDateTime.getLocalDateTime().
=> [BUG]: #2170: Fix failing test and added test for HoDateTime.getLocalDateTime()

src/main/java/core/module/IModule.java
Remove redundant modifiers for interfaces.
=> refactor: Remove redundant modifiers for interfaces

src/main/java/core/gui/DebugMode.java
Making DebugMode to an utility class.
=> refactor: Making DebugMode to an utility class

src/main/java/core/specialevents/SpecialEventsPredictionManager.java, src/main/java/module/ifa/FlagLabel.java, src/main/java/module/ifa/IfaOverviewDialog.java, src/main/java/module/ifa/table/SummaryTableSorter.java, src/main/java/module/lineup/penalties/PenaltyTakersView.java, src/main/java/module/lineup/substitution/SubstitutionOverview.java, src/main/java/module/lineup/substitution/WhenTextField.java, src/main/java/module/specialEvents/FilterPanel.java, src/main/java/module/teamAnalyzer/ui/RecapTableSorter.java, src/main/java/module/training/ui/TrainingPanel.java, src/main/java/module/tsforecast/Curve.java
=> refactor: Making inner classes static

src/main/java/core/net/DownloadFilter.java
Use functional style for single expression.
=> refactor: Use functional style for single expression

src/main/java/core/db/frontend/SQLDialog.java, src/main/java/core/db/frontend/TablesDialog.java, src/main/java/core/gui/LookAndFeelDialog.java
Center some dialogs over main window and capitalize menu entries in SQLDialog.
=> feat: Center some dialogs over main window and capitalize menu entries in SQLDialog

src/main/java/core/gui/model/PlayerOverviewTableModel.java, src/main/java/module/playerOverview/PlayerOverviewTable.java, src/main/resources/language/English.properties
=> #2119 Fix reinit of player overview table

src/main/java/core/gui/comp/table/HOTableModel.java
=> Fix HOTableModel.moveColumn illegal argument exception

src/main/java/module/youth/YouthPlayer.java, src/main/java/module/youth/YouthSkillInfo.java, src/main/java/module/youth/YouthSkillInfoColumn.java, src/main/java/module/youth/YouthSkillsInfo.java
Prepares youth max skill handling to implement #2117
=> #2117 YouthSkillInfo.maxValueRange

src/main/java/module/ifa/table/SummaryTableSorter.java, src/main/java/module/lineup/substitution/SubstitutionOverview.java, src/main/java/module/specialEvents/FilterPanel.java
Save memory by making a private inner class static
=> refactor: Save memory by making a private inner class static

src/main/java/core/gui/language/LanguageTableModel.java, src/main/java/module/teamAnalyzer/ui/ManualFilterTableRenderer.java, src/main/java/module/teamAnalyzer/ui/model/UiFilterTableModel.java, src/main/java/module/teamAnalyzer/ui/model/UiRosterTableModel.java
1. changes proposed in this pull request: Simlify basic if-statements.
=> refactor: Simlify basic if-statements

src/main/java/core/gui/language/LanguageTableModel.java, src/main/java/core/net/test/ConnTest.java, src/main/java/core/util/UnicodeConverter.java, src/main/java/module/ifa/gif/Quantize.java, src/main/java/module/specialEvents/FilterPanel.java, src/main/java/module/teamAnalyzer/manager/AppearanceComparator.java, src/main/java/module/teamAnalyzer/manager/MatchComparator.java, src/main/java/module/teamAnalyzer/manager/PerformanceComparator.java, src/main/java/module/teamAnalyzer/manager/RosterPlayerComparator.java, src/main/java/module/teamAnalyzer/report/PositionReport.java, src/main/java/module/teamAnalyzer/report/Report.java, src/main/java/module/teamAnalyzer/report/SpotReport.java, src/main/java/module/teamAnalyzer/report/TacticReport.java, src/main/java/module/teamAnalyzer/ui/model/UiFilterTableModel.java, src/main/java/module/teamAnalyzer/ui/model/UiRatingTableModel.java, src/main/java/module/teamAnalyzer/ui/model/UiRecapTableModel.java, src/main/java/module/teamAnalyzer/ui/model/UiRosterTableModel.java, src/main/java/module/teamAnalyzer/ui/renderer/RatingTableCellRenderer.java
=> docs: Fix Java doc issues

src/main/java/core/gui/HOMainFrame.java
The key change in this class is to make menu actions lambdas directly in the `addActionListener`, removing the `ActionListener` responsibility from the frame itself.  The menu items no longer need to be ivars, and were made local variables in the `initMenu` method.
One future improvement will be to move the business logic (`selectedPlayer`) away from this component, to clearly separate model and view.
cf. above.
=> Main Frame code cleanup.

src/main/java/module/series/MatchFixtures.java
=> Fix MatchFixtures.calculateTableEntry

src/main/java/core/db/StadionTable.java, src/main/java/core/db/StatisticQuery.java, src/main/java/module/misc/TeamPanel.java, src/main/java/tool/arenasizer/ArenaInfoPanel.java, src/main/java/tool/arenasizer/ArenaPanel.java, src/main/java/tool/arenasizer/ArenaSizer.java, src/main/java/tool/arenasizer/ArenaSizerDialog.java, src/main/java/tool/arenasizer/ControlPanel.java, src/main/java/tool/arenasizer/Stadium.java, src/main/resources/release_notes.md, src/test/java/tool/arenasizer/StadiumTest.java
This fixes #2219.  This also renames the fields in the stadium class to English for non-German speakers' understanding.
(per recent discussions, I turned on auto-formatting on IntelliJ, so apologies the PR contains lots of formatting changes as a result...)
- fixes issue #2219 
=> Fix / 0 when stadium under construction, and existing type is 0.

src/main/java/module/lineup/assistant/LineupAssistant.java, src/main/java/module/lineup/substitution/plausibility/PlausibilityCheck.java, src/main/resources/release_notes.md
=> #2224 Fix PlausibilityCheck.checkForProblem

src/main/java/core/gui/HOMainFrame.java, src/main/java/core/model/UserParameter.java, src/main/java/core/model/player/MatchRoleID.java, src/main/java/core/model/player/Player.java, src/main/java/module/lineup/Lineup.java, src/main/java/module/lineup/LineupPanel.java, src/main/java/module/lineup/assistant/LineupAssistant.java, src/main/java/module/lineup/assistant/LineupAssistantPanel.java, src/main/java/module/lineup/lineup/PlayerPositionPanel.java, src/main/resources/language/English.properties, src/main/resources/release_notes.md
=> #163 Refactor lineup assistant

src/main/java/core/gui/model/PlayerOverviewTableModel.kt
=> #2230 Fix IndexOutOfBoundsException in player overview

src/main/java/module/lineup/assistant/LineupAssistantPanel.java
=> #163 review

src/main/java/core/rating/RatingPredictionModel.java, src/main/resources/release_notes.md
=> #2237 Fix long shot rating calculation

src/main/java/tool/arenasizer/Stadium.java, src/main/resources/release_notes.md
=> #2239 Fix hrf import parse error

src/main/java/module/series/MatchFixtures.java, src/main/resources/release_notes.md
=> #2258 Fix MatchFixtures.findReplacementOfTeam

src/main/java/core/gui/comp/table/HOTableModel.kt
=> #2262 Fix HOTableModel.getRowOrderSettings

src/main/java/core/gui/comp/table/HOTableModel.kt, src/main/java/core/model/WorldDetailLeague.java, src/main/java/module/training/ui/model/OutputTableModel.java, src/main/resources/release_notes.md
=> #2265 Fix HOTableModel.moveColumn

src/main/java/core/db/XtraDataTable.java, src/main/java/core/model/XtraData.java
=> #2270 Fix XtraDataTable.initColumns

gradle.properties, src/main/resources/release_notes.md
=> #2088 release stable 9.0

docs/README.md, docs/latest.html, docs/latestbeta.html, docs/lateststable.html
=> #2088 master

docs/README.md, docs/latest.html, docs/latestbeta.html, docs/lateststable.html, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #2088 master continued

src/main/java/module/series/MatchFixtures.java, src/main/resources/release_notes.md
=> #2290 Fix MatchFixtures.findReplacementOfTeam

src/main/java/core/gui/comp/table/HOTableModel.kt, src/main/resources/release_notes.md
=> #2294 Fix array index out of bound exception in player overview

docs/README.md
=> Readme link to latest stable

build.gradle, gradle.properties, src/main/java/module/training/ui/model/SkillupTableModel.java, src/main/java/module/training/ui/renderer/SkillupTableRenderer.java, src/main/resources/release_notes.md
=> #2302 Fix SkillupTableModel.getSkillup

gradle.properties, src/main/java/core/file/xml/ConvertXml2Hrf.java, src/main/java/core/file/xml/XMLSpielplanParser.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #2307 Handle connection timeout errors

gradle.properties
=> Release HO 9.2

docs/README.md, src/main/java/core/model/UserParameter.java, src/main/java/core/option/GeneralSettingsPanel.java, src/main/java/core/util/AmountOfMoney.kt, src/main/java/module/series/promotion/PromotionInfoPanel.java, src/main/resources/language/English.properties
=> #2319 Fix general settings dialog layout

src/main/java/core/gui/comp/table/FixedColumnsTable.kt, src/main/java/core/model/HOConfigurationIntParameter.kt, src/main/java/core/model/WorldDetailLeague.java, src/main/java/core/model/WorldDetailsManager.java, src/main/java/core/option/GeneralSettingsPanel.java, src/main/java/core/option/OptionenDialog.java, src/main/java/core/util/AmountOfMoney.kt, src/main/java/module/opponentspy/SkillAdjuster.java, src/main/java/module/statistics/FinancesStatisticsPanel.java, src/main/java/module/transfer/transfertype/TransferTypePane.java, src/main/resources/release_notes.md
=> #2316 Fix currency settings error

build.gradle, gradle.properties, src/main/java/core/model/match/MatchLineupTeam.java, src/main/java/core/model/player/Player.java, src/main/resources/changelog.md, src/main/resources/release_notes.md
=> #2324 Fix subskill calculation when set pieces takers were replaced
