src/main/java/core/option/ReleaseChannelPanel.java
src/main/resources/sprache/English.properties

Changes proposed in this pull request:
Sets set line/word wrap to release channel text field in options to avoid overflow.   
Also removes awkward newlines.
Graphically changes this:
To that:
Changelog and release_notes:

set line/word wrap to release channel to avoid overflow

---

src/main/java/core/db/DBManager.java

I should have done it when I introduced `updateDBv23` while working on `transfer history panel`.   
May have partly caused (and hence fix) #72. Additionally fixes a bug that would surface when someone would try to use `transfer history panel` after updating from `stable 1.435` to `stable 1.436`. Database wouldn't have updated and there would be some errors (NullPointerException or sth).
2. changelog and release_notes

increment database version

---

docs/release_notes(dev).md
src/main/java/module/playeranalysis/experience/Spieler.java
src/main/java/module/playeranalysis/experience/Spielertabelle.java

Fix the exception throwed by opening the Experience tab of the PlayerAnalysis module.
It reverts a couple of excessive changes which get lost in the immense commit akasolace@8540ad6
Related to bug https://github.com/akasolace/HO/issues/105#issuecomment-475136413

Fix the exception throwed by opening the Experience tab of the PlayerAnalysis module.

---

src/main/java/core/gui/HOMainFrame.java

- fixes issue #177  
- [core/gui/HOMainFrame.java] has been updated

#177 - Standard shortcuts for copy/cut/paste don't work in MacOSX

---

build.gradle

- fixes issue #182 : Not correct building if it is launched from a branch
2. changelog and release_notes: do not require update
3. @akasolace I had to move the `def` into `doLast` in order to be able to use parameters from the `macAppBundle` plugin. I hope this is OK (as told, I'm new with Gradle)
I would ask you to check if a standard (full) build works, before accepting the pull request.
I only checked it on Mac (task `makeosX`) and it works fine (i.e. a single `.app` is created that crashes exatly as before the change, that is what is reported in #166).

Issue-182: Not correct building if it is launched from a branch

---

build.gradle

issue-198 Can't build OsX .app if Java 11 is the default version

---

src/main/java/core/file/FileLoader.java
src/main/java/core/model/FormulaFactors.java
src/main/java/core/rating/RatingPredictionConfig.java
src/main/java/core/rating/RatingPredictionParameter.java
src/main/java/core/training/SkillDrops.java

Changes proposed in this pull request:
- fixes issues #205 and #204 
Description
This introduce a new FileLoader that should be used in order to load resources (e.g. configuration files). The FileLoader searches requested files in the filesystem (e.g. for predictions) and, if they are not available, search for them into the HO.jar (or any other jar accessible by default from the classloader). This is needed because packaging the .app for MacOSX doesn't currently support resources outside JARs.
The FileLoader caches if a file has not been found, or where it should be searched next time it is loaded.
To be tested:
- set a log level to Debug
- first time a file is loaded via the FileLoader, the result (inside jar, outside jar, not found) is logged
Current tests passed before PR:
- MacOSX …

File loader

---

src/main/java/module/lineup/penalties/PenaltyTakersView.java

Automatically selection of penalty takers does not respect selection filtering #217 
Obviously, the other players (not in eleven and not reserve) are not considered.

Fix for #217

---

src/main/java/core/db/DBManager.java

changed the way DBManager checks for database existence

DBManager no longer throw when there's no database

---

docs/release_notes(dev).md
src/main/java/module/series/MatchDayPanel.java

`paarung` may not be initialised when the panel is loaded.  This exact
same statement appears above within the null check.
The latest release of HO cannot display the League details tab, and display the following error:
```
11:14:56 [Error]   core.util.ExceptionHandler: java.lang.NullPointerException
11:14:56 [Error]   core.util.ExceptionHandler: module.series.MatchDayPanel.setMatchButton(MatchDayPanel.java:127)
11:14:56 [Error]   core.util.ExceptionHandler: module.series.MatchDayPanel.fillLabels(MatchDayPanel.java:164)
11:14:56 [Error]   core.util.ExceptionHandler: module.series.MatchDayPanel.initComponents(MatchDayPanel.java:340)
11:14:56 [Error]   core.util.ExceptionHandler: module.series.MatchDayPanel.<init>(MatchDayPanel.java:61)
11:14:56 …
```

Fix NPE when opening League details panel

---

docs/release_notes(beta).md
docs/release_notes(dev).md
src/main/java/core/training/FutureTrainingManager.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

- fixes issue #296   
uses maximum trainingsspeed instead of average for marking trainees.

future trainings marking

---

src/main/java/core/model/player/Player.java

Fixes #411. `getShortName` is now used in `SpielerLabelEntry`, which
is used in various places, including in panels where the name may
potentially be empty, such as `TransferScoutPanel`.
- fixes issue #411 
This fixes a non-released feature.

Return empty string as-is in `getShortName`

---

src/main/java/module/lineup/Lineup.java

(cherry picked from commit 74deb0909560c8447ee0241b9499c72ee1d3b04c)
- fixes issue #415

bug#415 fix match order error if penalty takers list is incomplete

---

src/main/java/module/teamAnalyzer/ui/TeamAnalyzerPanel.java

Fixes #430. The `BorderLayout` places the components correctly, as
opposed to the `JSplitPane` which causes some issues based on the
original layout and possible the PLAF.
This also removes an extra `JPanel` which was containing the simulate
button, as it didn't seem to achieve anything.
- fixes issue #430 

Use `BorderLayout` to place simulate button.

---

src/main/java/core/gui/comp/table/TableSorter.java
src/main/java/module/lineup/AustellungSpielerTable.java
src/main/java/module/playerOverview/PlayerOverviewTable.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

This fixes #397 by making sure the default sorting for position is
descending which is the natural sorting for the HT positions.
Note this doesn't address the “remember the sorting” requirement as:
- The requirement was arising for the sorting by position bug,
- The “Default Arrangement” in Preferences > Misc is now honoured for all columns
so there is no more need for that requirement.
It also makes some improvements to `TableSorter`:
- Adds some documentation to clarify intent,
- Removes some unused code and general cleanup,
- Changes `Vector` to use `ArrayList`,
- Applies the third-click change to the list of players in “Lineup”
- fixes issue #397  
3. [Optional] suggested person to review this PR
@yaute74 …

Descending sort when sorting by “Best Position.”

---

src/main/java/module/series/promotion/HttpDataSubmitter.java
src/main/java/module/series/promotion/LeaguePromotionHandler.java
src/main/java/module/series/promotion/LeagueStatus.java
src/main/java/module/series/promotion/PromotionInfoPanel.java
src/main/resources/sprache/English.properties

Implement polling of league status during data processing until the Promotion/Demotion status is available. 
It also explicitly closes okhttp responses to solve possible “connection was leaked” error.

Poll status until league promotion status is available.

---

src/main/java/module/lineup/LineupPanel.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

Fixes #382 by using a split pane between the name column and the rest of the table.
- fixes issue #382 

Use a split pane for lineup table.

---

src/main/java/module/lineup/Lineup.java

Fixes #448.
This commit also changes the log level in case there is no match to
warning, and the name of the method in the error log in the catch is
now fixed.
- fixes issue #448 

Check if the list of matches is empty when checking for upcoming matches

---

src/main/java/core/model/UserParameter.java
src/main/java/core/option/SonstigeOptionenPanel.java
src/main/java/module/series/promotion/LeaguePromotionHandler.java
src/main/resources/sprache/English.properties

This adds a temporary option in the Preferences > Misc panel to turn on / off the promotion manager functionality to be able to test it outside week 14 & 15.
This option will be removed in later releases.

Add option for enabling promotion/demotion manager.

---

src/main/java/core/gui/comp/icon/DrawIcon.java
src/main/java/core/gui/theme/HOColorName.java
src/main/java/core/gui/theme/ho/HOClassicSchema.java
src/main/java/module/series/FormLabel.java
src/main/java/module/series/SeriesHistoryPanel.java
src/main/java/module/series/SeriesPanel.java
src/main/java/module/series/SeriesTablePanel.java
src/main/resources/changelog.md
src/main/resources/release_notes.md
src/main/resources/sprache/English.properties

Aspects of this were discussed in #238 .
This displays the form streak as coloured circles, instead of letters, e.g.:
By default it displays the 9 last results.  If there are fewer, it just does't display the unknown games, e.g.:
(Here all the results are green because I have hardcoded the value for testing)
Note that Home / Away is not visible any more; it is not useful to me, but it could be to others – we could potentially code Home matches with a vertical or horizontal line across the circle, if needs be.
I haven't updated the release notes yet, as this depends on whether we would want to include in the 3.0 beta, or a later version after the 3.0 release (probably better).
3. [Optional] suggested person to …

Display form streak using coloured circles.

---

src/main/java/core/db/DBManager.java
src/main/java/core/db/DBUpdater.java
src/main/java/core/util/TimeUtils.java

Fixes part of the issues raised in #471.  Matches make various queries
on MATCHHIGHLIGHTS, MATCHDETAILS and MATCHKURZINFO on fields that were
not indexed, causing perf issues.
- fixes issue #471 (the Matches tab perf issue)  

Add indices to improve Matches tab perf

---

src/main/java/core/db/JDBCAdapter.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

`COMPACT` causes major performance issues when exiting HO, without
significant benefits.  Only using a simple `SHUTDOWN` for now, this
can be turned back on later if needs be.
- fixes issue #471 

Simple `SHUTDOWN` of the database.

---

src/main/java/core/db/DBUpdater.java

follow up of f919b2ecc4cbf3c15aada4ebd6b280a0e6a0de89
This treats the case of uses who have already downloaded 3.0 BETA 1 and that will upgrade to BETA 2

fix matchkurzinfo column types for BETA 1 users

---

src/main/java/core/db/SpielerTable.java

The nickname and surname need to be escaped before inserting as they
may contain single quotes, which breaks the insert.
- fixes issue #490 

Escape player's nickname and surname when inserting.

---

src/main/java/module/playerOverview/SpielerTrainingsVergleichsPanel.java
src/main/java/module/playerOverview/TeamSummaryPanel.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

When downloading current details from the HT, the team summary needs
to be reset to display the current details, and be compared to the
previous ones.  Fixes #475.
- fixes issue #475 
3. [Optional] suggested person to review this PR @akasolace 
Can you please see if this the behaviour you are expecting after an update?  I am not entirely sure what we would want here after a new download, so for now I am displaying comparison between new team summary and previous one.

Compare team summary to previous one.

---

src/main/java/module/playerOverview/SpielerUebersichtsPanel.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

Waiting until the change is fully adjusted causes a small delay in
sync'ing the name table with the details table on the Squad table,
which is even more pronounced in dark mode, where painting is a bit
slower.  This commit removes the wait to make the change immediately.
This closes #465.
Also, the ivar `spielerUebersichTable` has been renamed
`playerOverviewTable` to reduce confusion.
- fixes issue #465 

Remove check to see if change is still adjusting.

---

src/main/java/core/net/DownloadDialog.java
src/main/java/module/playerOverview/SpielerDetailPanel.java

Fixes #516.  This makes sure the details of a team are downloaded
before downloading its matches so that the `teamId` is properly set.
This also adds a null check in `SpielerDetailPanel` following the
recent changes around last match date.
- fixes issue #516
3. [Optional] suggested person to review this PR @steffanots @akasolace

Ensure matches are downloaded on the first download.

---

src/main/java/module/series/SeriesPanel.java
src/main/java/module/series/promotion/PromotionInfoPanel.java
src/main/resources/sprache/English.properties

For teams playing playoffs for promotion / demotion, the message now displays the opposing team, and the potential new league, for example for those two Irish teams potentially playing each other: 
_Note that this requires changes to two labels in translations._

Display playoff opponent in status message.

---

src/main/java/core/gui/theme/BaseTheme.java
src/main/java/core/gui/theme/dark/DarkTheme.java
src/main/java/core/gui/theme/light/SolarizedLightTheme.java
src/main/java/core/gui/theme/nimbus/NimbusTheme.java

This PR generalises the font handling across all themes, identical to what is done to Nimbus.
This will hopefully solve the issue with CJK characters handling on different platforms.
@akasolace Would you be able to please check if this fixes the display issues on your system for Zheng Haiguo?

Handle font management identically across themes.

---

src/main/java/core/gui/theme/ImageUtilities.java

The new SVG icons for the jerseys are not cached by the `ThemeManager`, which is an oversight, and causes performance issues in Squad and Lineup tabs.   This PR adds the icon to the cache, like for other icons.

Cache jersey icons when they are loaded.

---

src/main/java/core/gui/comp/tabbedPane/TabCloseIcon.java

Following upgrade to Java 11, the close button on the tab is
truncated.  This sets the full width of the icon to the width of the
image plus the offset used to separate the icon from the text.
Cf. above. 

Fix issue with truncated close button on Nimbus.

---

build.gradle
src/main/java/core/net/DownloadDialog.java

These are small tweaks to get a nice appearance with Nimbus on Linux:
After changes, this looks like:
The PR also updates the version of darklaf to ensure all the recent bugfixes are integrated.
Cf. above.

Make diverse options panel an ImagePanel for consistency

---

src/main/java/core/gui/HOMainFrame.java
src/main/java/core/net/MyConnector.java
src/main/java/core/net/login/OAuthDialog.java
src/main/resources/changelog.md
src/main/resources/release_notes.md
version.properties

Under certain conditions HOMainFrame constructor ends up calling
`HOMainFrame.instance()` which in turn calls the HOMainFrame
constructor, as the null check of the singleton pattern is still
null (the constructor has not completed yet).
This PR ensures the main frame is not loading before display the OAuth
dialog is created.  If it still is loading, the dialog is created with
a null window, which should only cause the dialog to not be centered.
(This PR is for the 3.x release branch – I will create a separate PR for master tomorrow)
- fixes issue #584 (partly)

Ensure the HOMainFrame does not call itself whilst still loading.

---

src/main/java/core/gui/HOMainFrame.java
src/main/java/core/model/UserParameter.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

When calculating the width to be saved in the user parameters upon
exiting HO, the width of the screen is calculated as the min of the
current width and the difference between the width of the current
screen minus the current X location of the screen.
In a setup where multiple screens are present, the leftmost X may not
be 0 (e.g. X = 1096), causing the difference `width_screen -
current_pos_x` to be ridiculously small, and being stored as the
current width. (Ditto for height)
This commit offsets the difference with the leftmost X of the screen
to take into account multiple screens.
This commit also:
- translates some the comments in German into English;
- removes the deprecated user parameter `bestPostWidth` which seems to
never be read.
- fixes …

Calculate width with coords of left and top of current screen.

---

build.gradle
src/main/resources/changelog.md
src/main/resources/release_notes.md

Fixes #589.  Dependencies seem to be retrieved from resources, but
they would need to be copied manually there first.  This commit copies
dependencies into `lib/ho`.
This fix is for 3.x only, as it is expected that install4j handles dependencies will handle dependencies for us in 4.x+.
- fixes issue #589 

Copy dependencies into build dir.

---

src/main/java/core/option/ReleaseChannelPanel.java

For some reason (which I have no time to look into), when
displaying "Release Channel" panel in options, the text area's width
is being drawn by darklaf with an excessive width, causing display
issues in the panel.
Setting the preferred size on the text area solves the problem.
This PR also adds an empty border on the panel to avoid the help text to be set against the left side.
- fixes issue #648

Set a preferred size to avoid display issues.

---

src/main/java/core/gui/theme/HOColorName.java
src/main/java/core/gui/theme/ho/HOClassicSchema.java
src/main/java/module/series/SeriesPanel.java
src/main/java/module/series/promotion/DataSubmitter.java
src/main/java/module/series/promotion/HttpDataSubmitter.java
src/main/java/module/series/promotion/LeaguePromotionHandler.java
src/main/java/module/series/promotion/PromotionInfoPanel.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

Currently the only message displayed is the one below, due to #651 .
(Also use optional for handling potentially null values)
What do you think @akasolace ? 
- fixes issue #521

Display promotion status messages in red.

---

src/main/java/core/util/HTCalendarFactory.java
src/main/java/module/training/EffectDAO.java
src/main/java/module/training/PastTrainingManager.java
src/main/java/module/training/ui/AnalyzerPanel.java
src/main/java/module/training/ui/model/TrainingModel.java
src/main/resources/changelog.md
src/main/resources/release_notes.md

- fixes issue #539  
3. [Optional] suggested person to review this PR @akasolace 
How to verify this pull request:
in week 16 downloads
1. before economy date HO V3 and V4(with this PR) should show HTSeason 75 in training effect table
2. after economy date, but before training date HO 3 shows HTSeason 74; V4(with PR) correctly shows HTSeason 75
3. if i'm wrong with 2.; after training date but before match date HO 3 shows HTSeason 74; V4(with PR) correctly shows HTSeason 75.
4. after Match date both versions will show correctly HTSeason 76

#539 fix ht season correction

---

src/main/java/core/gui/model/PlayerCBItemRenderer.java

In statistics panel, there could be some null elements in the dropdown list

Reintroduce rendering of null element in PlayerCBItemRenderer

---

src/main/java/core/gui/HOMainFrame.java

This commit adds some logging to `windowClosing` and `windowClosed` to ensure the two are correctly called, and determine the root cause of issue #811 .

Add some logging for troubleshooting #811

---

src/main/java/core/db/DBUpdater.java
src/main/java/core/db/MatchDetailsTable.java
src/main/java/core/file/xml/ConvertXml2Hrf.java
src/main/java/core/file/xml/XMLManager.java
src/main/java/core/file/xml/XMLMatchdetailsParser.java
src/main/java/core/file/xml/XMLTeamDetailsParser.java
src/main/java/core/file/xml/xmlPlayersParser.java
src/main/java/core/model/match/Matchdetails.java
src/main/java/core/net/OnlineWorker.java
src/main/java/core/training/TrainingWeekManager.java
src/main/java/core/util/HelperWrapper.java
src/main/java/module/lineup/AustellungSpielerTable.java
src/main/java/module/teamAnalyzer/ui/FilterPanel.java

Also, avoid exceptions in XML parsing for better efficiency.
This change stores team formations in the db, as formation was not appearing any more in Team Analysis tab.

Store teams formations in match details.

---

src/main/java/module/lineup/ratings/LineupRatingPanel.java
src/main/java/module/lineup/ratings/MinuteTogglerPanel.java
version.properties

Explicitly retrieve image when darklaf is used, as image only gets loaded after interacting with UI.

Solve issue with image loading in darklaf.

---

src/main/java/core/gui/theme/ThemeManager.java
src/main/java/module/lineup/ratings/MinuteTogglerPanel.java

This PR generalises the fix for images that do not load until an action is performed in darklak (`DerivableImageIcon` seems to delay load)

Generalise fix to apply to all scaled icons.

---

src/main/java/core/training/TrainingManager.java
src/main/java/core/training/TrainingWeekManager.java

adds a method updateHistoricalTrainings() in training manager 
- ensure training table gets regularly updated by introducing new method updateHistoricalTrainings() in training manager.
- I suggest this function is called at the end of subskill calculation (to be done)

continuous update of Training table

---

src/main/java/core/model/HOModel.java
src/main/java/core/model/player/Player.java
src/main/java/core/net/DownloadDialog.java
version.properties

store recent trainings (since last download) in database during download.
calc subskills takes this new downloaded trainings into account.
training panel is NOT refreshed after download - the new training is not displayed

#903 store training since last download

---

src/main/java/core/db/DBConfigUpdater.java
src/main/java/core/training/TrainingManager.java
src/main/java/core/training/TrainingPerPlayer.java
src/main/java/core/training/TrainingPerWeek.java
src/main/java/core/training/TrainingWeekManager.java

introduce methods computeHistoricalTrainingsInclMatches() and getTrainingsBetweenDates() in training manager to ensure minimum impact on existing subskill recalculation methid
if you have initial date = currentDate - 7 weeks
we need to call once `computeHistoricalTrainingsInclMatches(initial_date)`
then we can do bunch of call as follow `getTrainingsBetweenDates(startDate, endDate)`
startdate will need obviously to be >= initial_date
the idea is to initilize the vector only once
that limit call to the database

uttility function in training manager to support subskill recalculate

---

src/main/java/core/db/DBManager.java
src/main/java/core/db/DBUpdater.java
src/main/java/core/db/MatchesKurzInfoTable.java
src/main/java/core/db/SpielerTable.java
src/main/java/core/file/hrf/HRFFileParser.java
src/main/java/core/file/hrf/HRFImport.java
src/main/java/core/file/hrf/HRFStringParser.java
src/main/java/core/file/xml/ConvertXml2Hrf.java
src/main/java/core/file/xml/XMLPlayersParser.java
src/main/java/core/model/match/MatchKurzInfo.java
src/main/java/core/model/player/Player.java
src/main/java/module/teamAnalyzer/ht/HattrickManager.java

This PR stores `LastMatchType` in the `SPIELER` table to get around an issue with matches ID overlapping.

Store LastMatch_Type in SPIELER table.

---

.github/workflows/release-beta.yml
.github/workflows/release-dev.yml
.github/workflows/release.yml
build.gradle
version.properties

For the pipeline to kick off, a tag must be created:
- v<major>.<minor>.<patch>-dev for a dev release;
- v<major>.<minor>.<patch>-beta for a beta release;
- v<major>.<minor>.<patch> for a stable release.
It creates an automated release in Github based on a the version of
the Gradle project.  All the artefacts under `build/artefacts/` are
attached to the build.
The build process requires two secrets to be installed in the
repository:
- A github token `RELEASE_TOKEN`, with release write permissions;
- A valid install4j license `INSTALL4J_LICENSE`.
(I don't have permissions to set those Secrets in this project)
cf. above.
3. [Optional] suggested person to review this PR @akasolace  @wsbrenk

Automated release pipeline.

---

.github/workflows/release-beta.yml
.github/workflows/release-dev.yml
.github/workflows/release.yml
build.gradle
version.properties

As the release process is now done using GitHub actions, the dedicated
gradle functions have been removed.  The releases also now include the
release notes in their description.
cf. above

Tweak release process to use dev, beta and stable tags.

---

docs/latest.html

forward old latest.html to the new update process. 
Updates of the new HO version no longer require latest.html to find new version (they will use the version.properties in the download folders).
HO versions prior to 3723 will use this latest.html to find the new update.

latest.html release current dev 3723

---

src/main/java/core/HO.java
src/main/resources/release_notes.md

This fixes #1291.  User preferences are only saved upon exiting HO, which calls
the `HOMainFrame#shutdown`.  On macos, when closing the app using Cmd+Q, it just
shuts down the JVM without performing the window closing handler.
The change ensures window closing events are triggered when using Cmd+Q.
- fixes issue #1291 

Invoke close window handler when exiting app on macos.

---

src/main/java/module/tsforecast/ForecastCurve.java

#1383 ForecastCurve.readPastMatches fix concurrent exception

---

src/main/java/core/db/SpielerTable.java

#1542 SpielerTable.createObject load subexperience as double

---

src/main/java/core/gui/model/PlayerAnalysisModel.java
src/main/java/core/gui/model/PlayerOverviewModel.java
src/main/resources/release_notes.md

Fixes #1757, although this should probably be further improved by ensuring that if no column is selected, at least a default set of “core” columns still appear, like nationality, etc.
This was caused by the fact that there was no `UserColumn` to be displayed, as by default all columns are marked as `canDisplay` `false`.  This fix ensures that upon first start all columns are displayed, therefore the `UserColumnsTable` gets populated.  Subsequently the user can select the columns to show or hide.  Again we should either prevent the user from de-selecting everything, or not blow up when the user selects nothing (probably the better solution).
- fixes issue #1757 
3. [Optional] suggested person to review this PR …

Do not return `true` when the application first starts

---

src/main/java/module/series/promotion/LeaguePromotionHandler.java
src/main/resources/release_notes.md

disables the league promotion handler. Should be reset when ht server is working again.

#1412 disable league promotion

---

docs/installing_ho.rst

The reference to second_team had double back ticks instead of single

fixing reference to `second_team` in installing_ho.rst

---

docs/lateststable.html

creating the release/7 branch destroyed the tag_stable download.
Rebuild should fix that.

rebuild stable HO7

---

src/main/java/core/gui/theme/ThemeManager.java
src/main/java/core/gui/theme/gnome/GnomeTheme.java
src/main/java/core/gui/theme/nimbus/NimbusTheme.java
src/main/resources/release_notes.md

The default layout (Nimbus) does not look very good on Linux, in particular the colour of the panels, and the scrollbars.  This PR provides a very simple theme, based on the Gtk L&F to make HO a bit less out of place on Gnome env.
Before:
After:

Add a Linux-friendly theme, called Gnome.

---

.github/workflows/release-dev.yml
build.gradle
src/main/resources/release_notes.md
utils/buildResources/HO.install4j

This is an attempt at fixing issue #1849 by updating install4j to the latest version, as it is unclear at this point what is causing the install to hang on some MacOS machines.
See above, see if this fixes #1849 

Update install4j version to 10.0.6

---

build.gradle

The `clean` task is called after `compileKotlin`, and before `compileJava`, causing the output of the Kotlin compilation to be wiped, and therefore not made available to the Java compilation.
This commit re-orders tasks to get `clean` done before the other tasks for `compileJava`.  Hopefully, this should solve the build issues encountered with Kotlin in the Github workflow...
This commit also verifies the presence of the `INSTALL4J_HOME` env var to avoid compile issue when checking out the project the first time.
cf. above

Change order of Gradle tasks.

---

src/main/java/core/db/TransferTable.java
src/main/resources/release_notes.md

Fix #1965
- fixes issue #1965 

Correct operator, and typo in column name in SQL query.

---

src/main/java/core/model/player/SkillChange.java

- fixes error in training prediction when league's locale season differs from swedish league

fix SkillChange.getHtSeason

---

build.gradle
src/main/resources/release_notes.md

Jar extension sets the version in an eager fashion, thus not taking into account the version as it is computed by `createVersion`.  This commit overrides the jar manifest version once it has been defined.
- fixes issue #2002 

Override version in jar manifest in `createVersion`.

---

src/main/java/core/net/login/OAuthDialog.java
src/main/resources/release_notes.md

- fixes issue #1471
3. [Optional] suggested person to review this PR @tychobrailleur : Do you think it is a good idea replacing JTextfields with awt.Textfield?

#1471 enable standard popup menus in oauth dialog's text fields

---

gradle.properties

#1797 create beta

---

build.gradle

This fixes CVE-2023-3635, cf. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3635
cf. above

Update dependencies, in particular OkHttp to fix CVE.

---

src/main/java/core/db/DBManager.java
src/main/java/core/db/IfaMatchTable.java
src/main/java/core/db/WorldDetailsTable.java
src/main/java/core/model/WorldDetailsManager.java
src/main/java/core/net/MyConnector.java
src/main/java/module/ifa/RightPanel.java
src/main/resources/release_notes.md

#2063 download missing world details

---

.github/workflows/release-dev.yml
src/main/resources/release_notes.md

- fixes issue #2081 , this cherry-picks change in 8d8365b

Create `stable` tag when `tag_stable` is created. (#2081)

---

src/main/java/core/option/FormelPanel.java
src/main/resources/release_notes.md

- 'Preferences/Formulas': When changing anything and saving it, the application does not crash anymore during quit.

fix: Prevent exception on saving a change in the 'Formulas'

---

src/main/java/core/model/Translator.java
src/test/java/core/constants/player/PlayerAbilityTest.kt
src/test/java/core/util/HODateTimeTest.java

Correcting PlayerAbilityTest due to refactoring of the translation functionality that was committed with 381835ecbd1c4b05079149dbbd2e343eca3f6e5c
- corrects the PlayerAbilityTest by introducing a Translator.NoTranslation that means no translation

fix: correcting PlayerAbilityTest due to refactoring of the translation functionality

---

src/main/java/core/file/ExampleFileFilter.java
src/main/java/core/file/ZipHelper.java
src/main/java/core/file/hrf/HRFStringParser.java
src/main/java/core/model/series/Liga.java
src/main/java/core/net/DownloadDialog.java
src/main/java/core/net/MyConnector.java
src/main/java/core/net/OnlineWorker.java
src/main/java/core/option/InitOptionsDialog.java
src/main/java/core/option/ReleaseChannelPanel.java
src/main/java/core/rating/RatingPredictionParameter.java
src/main/java/core/util/Helper.java
src/main/java/module/transfer/scout/PlayerConverter.java
src/main/java/tool/arenasizer/Stadium.java

- Use import of class from java.util or remove superfluous qualification

Refactor: Use import of class from java.util or remove superfluous qualification

---

src/main/java/core/net/DownloadDialog.java
src/main/resources/release_notes.md

[BUG] #2137: Download dialog does not reappear after being closed using the 'X' button

---

src/main/java/core/util/HODateTime.java
src/test/java/core/util/HODateTimeTest.java

- The contract of the 'equals' and 'hashCode' function of class 'HODateTime' was violated. It is now possible to use e.g. 'HODateTime' in 'HashSet' or in native test code for equality checks.

Fix: Correct contract of equals and hashCode of HODateTime

---

docs/contributing.md

Docs: Fix typo and use heading for #9

---

src/main/resources/release_notes.md

- fixes issue #2139
I've made the changes also in POEditor...

[BUG] #2139: Fix wrong translation for Spanish for 'worstOfSeason'

---

src/test/java/core/util/HODateTimeTest.java

- Use AssertJ API in HODateTimeTest because it is better readable

test: Use AssertJ API in HODateTimeTest

---

src/main/java/core/gui/theme/FontUtil.java
src/main/java/core/gui/theme/ImageUtilities.java
src/main/java/core/util/CurrencyUtils.java
src/main/java/core/util/DateTimeUtils.java
src/main/java/core/util/ExceptionUtils.java
src/main/java/core/util/GUIUtils.java
src/main/java/core/util/Helper.java
src/main/java/core/util/IOUtils.java
src/main/java/core/util/MathUtils.java
src/main/java/core/util/OSUtils.java
src/main/java/core/util/StringUtils.java
src/main/java/core/util/XMLUtils.java
src/main/java/module/ifa/PluginIfaUtils.java
src/main/java/module/nthrf/NthrfUtil.java
src/main/java/module/teamAnalyzer/ui/RatingUtil.java

Standardizing means that the utility class has a private constructor that throws UnsupportedOperationException to make clear that there is never the intension to have an instance of that class.

refactor: Standardize utility classes

---

src/main/java/module/matches/SpielerSternePanel.java

Since final classes cannot be inherited, marking a method as final may be unnecessary and confusing.

refactor: Remove confusing final modifier

---

src/main/java/core/gui/language/LanguageTableModel.java
src/main/java/core/net/test/ConnTest.java
src/main/java/core/util/UTF8Control.java
src/main/java/core/util/UnicodeConverter.java

Use constant StandardCharsets.UTF_8 and StandardCharsets.UTF_16 instead of literal.

refactor: Use constant StandardCharsets.UTF_8 and StandardCharsets.UTF_16 instead of literal

---

src/main/java/core/gui/comp/table/FixedColumnsTable.java
src/main/java/core/gui/comp/table/HOTableModel.java
src/main/java/module/lineup/LineupPlayersTable.java
src/main/java/module/playerOverview/PlayerOverviewTable.java
src/main/java/module/youth/YouthPlayerView.java

Fix youthplayer table

---

src/main/java/core/gui/language/LanguageTableModel.java

Fix typo: 'language' instead of 'langauage'

refactor: Typo: 'language' instead of 'langauage'
